// Midterm.v

// Generated using ACDS version 23.1 991

`timescale 1 ps / 1 ps
module Midterm (
		input  wire [3:0]  buttons_buttons,   //    buttons.buttons
		input  wire        clk_clk,           //        clk.clk
		output wire [6:0]  hex0_segs,         //       hex0.segs
		output wire [6:0]  hex1_segs,         //       hex1.segs
		output wire [6:0]  hex2_segs,         //       hex2.segs
		output wire [6:0]  hex3_segs,         //       hex3.segs
		output wire [6:0]  hex4_segs,         //       hex4.segs
		output wire [6:0]  hex5_segs,         //       hex5.segs
		output wire [9:0]  leds_leds,         //       leds.leds
		output wire        sdram_clk_clk,     //  sdram_clk.clk
		output wire [12:0] sdram_wire_addr,   // sdram_wire.addr
		output wire [1:0]  sdram_wire_ba,     //           .ba
		output wire        sdram_wire_cas_n,  //           .cas_n
		output wire        sdram_wire_cke,    //           .cke
		output wire        sdram_wire_cs_n,   //           .cs_n
		inout  wire [15:0] sdram_wire_dq,     //           .dq
		output wire [1:0]  sdram_wire_dqm,    //           .dqm
		output wire        sdram_wire_ras_n,  //           .ras_n
		output wire        sdram_wire_we_n,   //           .we_n
		input  wire [9:0]  switches_switches  //   switches.switches
	);

	wire         clocks_sys_clk_clk;                                            // CLOCKS:sys_clk_clk -> [BUTTONS_0:clk, DEBUG:clk, LEDs:clk, NiosV_FreeRTOS:clk, SDRAM:clk, SEG7s_0:clk, SEG7s_1:clk, SEG7s_2:clk, SEG7s_3:clk, SEG7s_4:clk, SEG7s_5:clk, SWITCHES_0:clk, irq_mapper:clk, mm_interconnect_0:CLOCKS_sys_clk_clk, rst_controller:clk]
	wire         niosv_freertos_dbg_reset_out_reset;                            // NiosV_FreeRTOS:dbg_reset_out_reset -> [CLOCKS:ref_reset_reset, NiosV_FreeRTOS:ndm_reset_in_reset, rst_controller:reset_in0]
	wire  [31:0] niosv_freertos_data_manager_awaddr;                            // NiosV_FreeRTOS:data_manager_awaddr -> mm_interconnect_0:NiosV_FreeRTOS_data_manager_awaddr
	wire   [1:0] niosv_freertos_data_manager_bresp;                             // mm_interconnect_0:NiosV_FreeRTOS_data_manager_bresp -> NiosV_FreeRTOS:data_manager_bresp
	wire         niosv_freertos_data_manager_arready;                           // mm_interconnect_0:NiosV_FreeRTOS_data_manager_arready -> NiosV_FreeRTOS:data_manager_arready
	wire  [31:0] niosv_freertos_data_manager_rdata;                             // mm_interconnect_0:NiosV_FreeRTOS_data_manager_rdata -> NiosV_FreeRTOS:data_manager_rdata
	wire   [3:0] niosv_freertos_data_manager_wstrb;                             // NiosV_FreeRTOS:data_manager_wstrb -> mm_interconnect_0:NiosV_FreeRTOS_data_manager_wstrb
	wire         niosv_freertos_data_manager_wready;                            // mm_interconnect_0:NiosV_FreeRTOS_data_manager_wready -> NiosV_FreeRTOS:data_manager_wready
	wire         niosv_freertos_data_manager_awready;                           // mm_interconnect_0:NiosV_FreeRTOS_data_manager_awready -> NiosV_FreeRTOS:data_manager_awready
	wire         niosv_freertos_data_manager_rready;                            // NiosV_FreeRTOS:data_manager_rready -> mm_interconnect_0:NiosV_FreeRTOS_data_manager_rready
	wire         niosv_freertos_data_manager_bready;                            // NiosV_FreeRTOS:data_manager_bready -> mm_interconnect_0:NiosV_FreeRTOS_data_manager_bready
	wire         niosv_freertos_data_manager_wvalid;                            // NiosV_FreeRTOS:data_manager_wvalid -> mm_interconnect_0:NiosV_FreeRTOS_data_manager_wvalid
	wire  [31:0] niosv_freertos_data_manager_araddr;                            // NiosV_FreeRTOS:data_manager_araddr -> mm_interconnect_0:NiosV_FreeRTOS_data_manager_araddr
	wire   [2:0] niosv_freertos_data_manager_arprot;                            // NiosV_FreeRTOS:data_manager_arprot -> mm_interconnect_0:NiosV_FreeRTOS_data_manager_arprot
	wire   [1:0] niosv_freertos_data_manager_rresp;                             // mm_interconnect_0:NiosV_FreeRTOS_data_manager_rresp -> NiosV_FreeRTOS:data_manager_rresp
	wire   [2:0] niosv_freertos_data_manager_awprot;                            // NiosV_FreeRTOS:data_manager_awprot -> mm_interconnect_0:NiosV_FreeRTOS_data_manager_awprot
	wire  [31:0] niosv_freertos_data_manager_wdata;                             // NiosV_FreeRTOS:data_manager_wdata -> mm_interconnect_0:NiosV_FreeRTOS_data_manager_wdata
	wire         niosv_freertos_data_manager_arvalid;                           // NiosV_FreeRTOS:data_manager_arvalid -> mm_interconnect_0:NiosV_FreeRTOS_data_manager_arvalid
	wire         niosv_freertos_data_manager_bvalid;                            // mm_interconnect_0:NiosV_FreeRTOS_data_manager_bvalid -> NiosV_FreeRTOS:data_manager_bvalid
	wire         niosv_freertos_data_manager_awvalid;                           // NiosV_FreeRTOS:data_manager_awvalid -> mm_interconnect_0:NiosV_FreeRTOS_data_manager_awvalid
	wire         niosv_freertos_data_manager_rvalid;                            // mm_interconnect_0:NiosV_FreeRTOS_data_manager_rvalid -> NiosV_FreeRTOS:data_manager_rvalid
	wire  [31:0] niosv_freertos_instruction_manager_awaddr;                     // NiosV_FreeRTOS:instruction_manager_awaddr -> mm_interconnect_0:NiosV_FreeRTOS_instruction_manager_awaddr
	wire   [1:0] niosv_freertos_instruction_manager_bresp;                      // mm_interconnect_0:NiosV_FreeRTOS_instruction_manager_bresp -> NiosV_FreeRTOS:instruction_manager_bresp
	wire         niosv_freertos_instruction_manager_arready;                    // mm_interconnect_0:NiosV_FreeRTOS_instruction_manager_arready -> NiosV_FreeRTOS:instruction_manager_arready
	wire  [31:0] niosv_freertos_instruction_manager_rdata;                      // mm_interconnect_0:NiosV_FreeRTOS_instruction_manager_rdata -> NiosV_FreeRTOS:instruction_manager_rdata
	wire   [3:0] niosv_freertos_instruction_manager_wstrb;                      // NiosV_FreeRTOS:instruction_manager_wstrb -> mm_interconnect_0:NiosV_FreeRTOS_instruction_manager_wstrb
	wire         niosv_freertos_instruction_manager_wready;                     // mm_interconnect_0:NiosV_FreeRTOS_instruction_manager_wready -> NiosV_FreeRTOS:instruction_manager_wready
	wire         niosv_freertos_instruction_manager_awready;                    // mm_interconnect_0:NiosV_FreeRTOS_instruction_manager_awready -> NiosV_FreeRTOS:instruction_manager_awready
	wire         niosv_freertos_instruction_manager_rready;                     // NiosV_FreeRTOS:instruction_manager_rready -> mm_interconnect_0:NiosV_FreeRTOS_instruction_manager_rready
	wire         niosv_freertos_instruction_manager_bready;                     // NiosV_FreeRTOS:instruction_manager_bready -> mm_interconnect_0:NiosV_FreeRTOS_instruction_manager_bready
	wire         niosv_freertos_instruction_manager_wvalid;                     // NiosV_FreeRTOS:instruction_manager_wvalid -> mm_interconnect_0:NiosV_FreeRTOS_instruction_manager_wvalid
	wire  [31:0] niosv_freertos_instruction_manager_araddr;                     // NiosV_FreeRTOS:instruction_manager_araddr -> mm_interconnect_0:NiosV_FreeRTOS_instruction_manager_araddr
	wire   [2:0] niosv_freertos_instruction_manager_arprot;                     // NiosV_FreeRTOS:instruction_manager_arprot -> mm_interconnect_0:NiosV_FreeRTOS_instruction_manager_arprot
	wire   [1:0] niosv_freertos_instruction_manager_rresp;                      // mm_interconnect_0:NiosV_FreeRTOS_instruction_manager_rresp -> NiosV_FreeRTOS:instruction_manager_rresp
	wire   [2:0] niosv_freertos_instruction_manager_awprot;                     // NiosV_FreeRTOS:instruction_manager_awprot -> mm_interconnect_0:NiosV_FreeRTOS_instruction_manager_awprot
	wire  [31:0] niosv_freertos_instruction_manager_wdata;                      // NiosV_FreeRTOS:instruction_manager_wdata -> mm_interconnect_0:NiosV_FreeRTOS_instruction_manager_wdata
	wire         niosv_freertos_instruction_manager_arvalid;                    // NiosV_FreeRTOS:instruction_manager_arvalid -> mm_interconnect_0:NiosV_FreeRTOS_instruction_manager_arvalid
	wire         niosv_freertos_instruction_manager_bvalid;                     // mm_interconnect_0:NiosV_FreeRTOS_instruction_manager_bvalid -> NiosV_FreeRTOS:instruction_manager_bvalid
	wire         niosv_freertos_instruction_manager_awvalid;                    // NiosV_FreeRTOS:instruction_manager_awvalid -> mm_interconnect_0:NiosV_FreeRTOS_instruction_manager_awvalid
	wire         niosv_freertos_instruction_manager_rvalid;                     // mm_interconnect_0:NiosV_FreeRTOS_instruction_manager_rvalid -> NiosV_FreeRTOS:instruction_manager_rvalid
	wire         mm_interconnect_0_debug_avalon_jtag_slave_chipselect;          // mm_interconnect_0:DEBUG_avalon_jtag_slave_chipselect -> DEBUG:av_chipselect
	wire  [31:0] mm_interconnect_0_debug_avalon_jtag_slave_readdata;            // DEBUG:av_readdata -> mm_interconnect_0:DEBUG_avalon_jtag_slave_readdata
	wire         mm_interconnect_0_debug_avalon_jtag_slave_waitrequest;         // DEBUG:av_waitrequest -> mm_interconnect_0:DEBUG_avalon_jtag_slave_waitrequest
	wire   [0:0] mm_interconnect_0_debug_avalon_jtag_slave_address;             // mm_interconnect_0:DEBUG_avalon_jtag_slave_address -> DEBUG:av_address
	wire         mm_interconnect_0_debug_avalon_jtag_slave_read;                // mm_interconnect_0:DEBUG_avalon_jtag_slave_read -> DEBUG:av_read_n
	wire         mm_interconnect_0_debug_avalon_jtag_slave_write;               // mm_interconnect_0:DEBUG_avalon_jtag_slave_write -> DEBUG:av_write_n
	wire  [31:0] mm_interconnect_0_debug_avalon_jtag_slave_writedata;           // mm_interconnect_0:DEBUG_avalon_jtag_slave_writedata -> DEBUG:av_writedata
	wire         mm_interconnect_0_seg7s_0_avalon_slave_0_chipselect;           // mm_interconnect_0:SEG7s_0_avalon_slave_0_chipselect -> SEG7s_0:chipselect
	wire  [31:0] mm_interconnect_0_seg7s_0_avalon_slave_0_readdata;             // SEG7s_0:readdata -> mm_interconnect_0:SEG7s_0_avalon_slave_0_readdata
	wire   [1:0] mm_interconnect_0_seg7s_0_avalon_slave_0_address;              // mm_interconnect_0:SEG7s_0_avalon_slave_0_address -> SEG7s_0:address
	wire         mm_interconnect_0_seg7s_0_avalon_slave_0_read;                 // mm_interconnect_0:SEG7s_0_avalon_slave_0_read -> SEG7s_0:read
	wire         mm_interconnect_0_seg7s_0_avalon_slave_0_write;                // mm_interconnect_0:SEG7s_0_avalon_slave_0_write -> SEG7s_0:write
	wire  [31:0] mm_interconnect_0_seg7s_0_avalon_slave_0_writedata;            // mm_interconnect_0:SEG7s_0_avalon_slave_0_writedata -> SEG7s_0:writedata
	wire         mm_interconnect_0_seg7s_1_avalon_slave_0_chipselect;           // mm_interconnect_0:SEG7s_1_avalon_slave_0_chipselect -> SEG7s_1:chipselect
	wire  [31:0] mm_interconnect_0_seg7s_1_avalon_slave_0_readdata;             // SEG7s_1:readdata -> mm_interconnect_0:SEG7s_1_avalon_slave_0_readdata
	wire   [1:0] mm_interconnect_0_seg7s_1_avalon_slave_0_address;              // mm_interconnect_0:SEG7s_1_avalon_slave_0_address -> SEG7s_1:address
	wire         mm_interconnect_0_seg7s_1_avalon_slave_0_read;                 // mm_interconnect_0:SEG7s_1_avalon_slave_0_read -> SEG7s_1:read
	wire         mm_interconnect_0_seg7s_1_avalon_slave_0_write;                // mm_interconnect_0:SEG7s_1_avalon_slave_0_write -> SEG7s_1:write
	wire  [31:0] mm_interconnect_0_seg7s_1_avalon_slave_0_writedata;            // mm_interconnect_0:SEG7s_1_avalon_slave_0_writedata -> SEG7s_1:writedata
	wire         mm_interconnect_0_seg7s_2_avalon_slave_0_chipselect;           // mm_interconnect_0:SEG7s_2_avalon_slave_0_chipselect -> SEG7s_2:chipselect
	wire  [31:0] mm_interconnect_0_seg7s_2_avalon_slave_0_readdata;             // SEG7s_2:readdata -> mm_interconnect_0:SEG7s_2_avalon_slave_0_readdata
	wire   [1:0] mm_interconnect_0_seg7s_2_avalon_slave_0_address;              // mm_interconnect_0:SEG7s_2_avalon_slave_0_address -> SEG7s_2:address
	wire         mm_interconnect_0_seg7s_2_avalon_slave_0_read;                 // mm_interconnect_0:SEG7s_2_avalon_slave_0_read -> SEG7s_2:read
	wire         mm_interconnect_0_seg7s_2_avalon_slave_0_write;                // mm_interconnect_0:SEG7s_2_avalon_slave_0_write -> SEG7s_2:write
	wire  [31:0] mm_interconnect_0_seg7s_2_avalon_slave_0_writedata;            // mm_interconnect_0:SEG7s_2_avalon_slave_0_writedata -> SEG7s_2:writedata
	wire         mm_interconnect_0_seg7s_3_avalon_slave_0_chipselect;           // mm_interconnect_0:SEG7s_3_avalon_slave_0_chipselect -> SEG7s_3:chipselect
	wire  [31:0] mm_interconnect_0_seg7s_3_avalon_slave_0_readdata;             // SEG7s_3:readdata -> mm_interconnect_0:SEG7s_3_avalon_slave_0_readdata
	wire   [1:0] mm_interconnect_0_seg7s_3_avalon_slave_0_address;              // mm_interconnect_0:SEG7s_3_avalon_slave_0_address -> SEG7s_3:address
	wire         mm_interconnect_0_seg7s_3_avalon_slave_0_read;                 // mm_interconnect_0:SEG7s_3_avalon_slave_0_read -> SEG7s_3:read
	wire         mm_interconnect_0_seg7s_3_avalon_slave_0_write;                // mm_interconnect_0:SEG7s_3_avalon_slave_0_write -> SEG7s_3:write
	wire  [31:0] mm_interconnect_0_seg7s_3_avalon_slave_0_writedata;            // mm_interconnect_0:SEG7s_3_avalon_slave_0_writedata -> SEG7s_3:writedata
	wire         mm_interconnect_0_seg7s_4_avalon_slave_0_chipselect;           // mm_interconnect_0:SEG7s_4_avalon_slave_0_chipselect -> SEG7s_4:chipselect
	wire  [31:0] mm_interconnect_0_seg7s_4_avalon_slave_0_readdata;             // SEG7s_4:readdata -> mm_interconnect_0:SEG7s_4_avalon_slave_0_readdata
	wire   [1:0] mm_interconnect_0_seg7s_4_avalon_slave_0_address;              // mm_interconnect_0:SEG7s_4_avalon_slave_0_address -> SEG7s_4:address
	wire         mm_interconnect_0_seg7s_4_avalon_slave_0_read;                 // mm_interconnect_0:SEG7s_4_avalon_slave_0_read -> SEG7s_4:read
	wire         mm_interconnect_0_seg7s_4_avalon_slave_0_write;                // mm_interconnect_0:SEG7s_4_avalon_slave_0_write -> SEG7s_4:write
	wire  [31:0] mm_interconnect_0_seg7s_4_avalon_slave_0_writedata;            // mm_interconnect_0:SEG7s_4_avalon_slave_0_writedata -> SEG7s_4:writedata
	wire         mm_interconnect_0_seg7s_5_avalon_slave_0_chipselect;           // mm_interconnect_0:SEG7s_5_avalon_slave_0_chipselect -> SEG7s_5:chipselect
	wire  [31:0] mm_interconnect_0_seg7s_5_avalon_slave_0_readdata;             // SEG7s_5:readdata -> mm_interconnect_0:SEG7s_5_avalon_slave_0_readdata
	wire   [1:0] mm_interconnect_0_seg7s_5_avalon_slave_0_address;              // mm_interconnect_0:SEG7s_5_avalon_slave_0_address -> SEG7s_5:address
	wire         mm_interconnect_0_seg7s_5_avalon_slave_0_read;                 // mm_interconnect_0:SEG7s_5_avalon_slave_0_read -> SEG7s_5:read
	wire         mm_interconnect_0_seg7s_5_avalon_slave_0_write;                // mm_interconnect_0:SEG7s_5_avalon_slave_0_write -> SEG7s_5:write
	wire  [31:0] mm_interconnect_0_seg7s_5_avalon_slave_0_writedata;            // mm_interconnect_0:SEG7s_5_avalon_slave_0_writedata -> SEG7s_5:writedata
	wire         mm_interconnect_0_switches_0_avalon_slave_0_chipselect;        // mm_interconnect_0:SWITCHES_0_avalon_slave_0_chipselect -> SWITCHES_0:chipselect
	wire  [31:0] mm_interconnect_0_switches_0_avalon_slave_0_readdata;          // SWITCHES_0:readdata -> mm_interconnect_0:SWITCHES_0_avalon_slave_0_readdata
	wire   [1:0] mm_interconnect_0_switches_0_avalon_slave_0_address;           // mm_interconnect_0:SWITCHES_0_avalon_slave_0_address -> SWITCHES_0:address
	wire         mm_interconnect_0_switches_0_avalon_slave_0_read;              // mm_interconnect_0:SWITCHES_0_avalon_slave_0_read -> SWITCHES_0:read
	wire         mm_interconnect_0_switches_0_avalon_slave_0_write;             // mm_interconnect_0:SWITCHES_0_avalon_slave_0_write -> SWITCHES_0:write
	wire  [31:0] mm_interconnect_0_switches_0_avalon_slave_0_writedata;         // mm_interconnect_0:SWITCHES_0_avalon_slave_0_writedata -> SWITCHES_0:writedata
	wire         mm_interconnect_0_buttons_0_avalon_slave_0_chipselect;         // mm_interconnect_0:BUTTONS_0_avalon_slave_0_chipselect -> BUTTONS_0:chipselect
	wire  [31:0] mm_interconnect_0_buttons_0_avalon_slave_0_readdata;           // BUTTONS_0:readdata -> mm_interconnect_0:BUTTONS_0_avalon_slave_0_readdata
	wire   [1:0] mm_interconnect_0_buttons_0_avalon_slave_0_address;            // mm_interconnect_0:BUTTONS_0_avalon_slave_0_address -> BUTTONS_0:address
	wire         mm_interconnect_0_buttons_0_avalon_slave_0_read;               // mm_interconnect_0:BUTTONS_0_avalon_slave_0_read -> BUTTONS_0:read
	wire         mm_interconnect_0_buttons_0_avalon_slave_0_write;              // mm_interconnect_0:BUTTONS_0_avalon_slave_0_write -> BUTTONS_0:write
	wire  [31:0] mm_interconnect_0_buttons_0_avalon_slave_0_writedata;          // mm_interconnect_0:BUTTONS_0_avalon_slave_0_writedata -> BUTTONS_0:writedata
	wire         mm_interconnect_0_leds_avalon_slave_0_1_chipselect;            // mm_interconnect_0:LEDs_avalon_slave_0_1_chipselect -> LEDs:chipselect
	wire  [31:0] mm_interconnect_0_leds_avalon_slave_0_1_readdata;              // LEDs:readdata -> mm_interconnect_0:LEDs_avalon_slave_0_1_readdata
	wire   [1:0] mm_interconnect_0_leds_avalon_slave_0_1_address;               // mm_interconnect_0:LEDs_avalon_slave_0_1_address -> LEDs:address
	wire         mm_interconnect_0_leds_avalon_slave_0_1_read;                  // mm_interconnect_0:LEDs_avalon_slave_0_1_read -> LEDs:read
	wire         mm_interconnect_0_leds_avalon_slave_0_1_write;                 // mm_interconnect_0:LEDs_avalon_slave_0_1_write -> LEDs:write
	wire  [31:0] mm_interconnect_0_leds_avalon_slave_0_1_writedata;             // mm_interconnect_0:LEDs_avalon_slave_0_1_writedata -> LEDs:writedata
	wire  [31:0] mm_interconnect_0_niosv_freertos_dm_agent_readdata;            // NiosV_FreeRTOS:dm_agent_readdata -> mm_interconnect_0:NiosV_FreeRTOS_dm_agent_readdata
	wire         mm_interconnect_0_niosv_freertos_dm_agent_waitrequest;         // NiosV_FreeRTOS:dm_agent_waitrequest -> mm_interconnect_0:NiosV_FreeRTOS_dm_agent_waitrequest
	wire  [15:0] mm_interconnect_0_niosv_freertos_dm_agent_address;             // mm_interconnect_0:NiosV_FreeRTOS_dm_agent_address -> NiosV_FreeRTOS:dm_agent_address
	wire         mm_interconnect_0_niosv_freertos_dm_agent_read;                // mm_interconnect_0:NiosV_FreeRTOS_dm_agent_read -> NiosV_FreeRTOS:dm_agent_read
	wire         mm_interconnect_0_niosv_freertos_dm_agent_readdatavalid;       // NiosV_FreeRTOS:dm_agent_readdatavalid -> mm_interconnect_0:NiosV_FreeRTOS_dm_agent_readdatavalid
	wire         mm_interconnect_0_niosv_freertos_dm_agent_write;               // mm_interconnect_0:NiosV_FreeRTOS_dm_agent_write -> NiosV_FreeRTOS:dm_agent_write
	wire  [31:0] mm_interconnect_0_niosv_freertos_dm_agent_writedata;           // mm_interconnect_0:NiosV_FreeRTOS_dm_agent_writedata -> NiosV_FreeRTOS:dm_agent_writedata
	wire         mm_interconnect_0_sdram_s1_chipselect;                         // mm_interconnect_0:SDRAM_s1_chipselect -> SDRAM:az_cs
	wire  [15:0] mm_interconnect_0_sdram_s1_readdata;                           // SDRAM:za_data -> mm_interconnect_0:SDRAM_s1_readdata
	wire         mm_interconnect_0_sdram_s1_waitrequest;                        // SDRAM:za_waitrequest -> mm_interconnect_0:SDRAM_s1_waitrequest
	wire  [24:0] mm_interconnect_0_sdram_s1_address;                            // mm_interconnect_0:SDRAM_s1_address -> SDRAM:az_addr
	wire         mm_interconnect_0_sdram_s1_read;                               // mm_interconnect_0:SDRAM_s1_read -> SDRAM:az_rd_n
	wire   [1:0] mm_interconnect_0_sdram_s1_byteenable;                         // mm_interconnect_0:SDRAM_s1_byteenable -> SDRAM:az_be_n
	wire         mm_interconnect_0_sdram_s1_readdatavalid;                      // SDRAM:za_valid -> mm_interconnect_0:SDRAM_s1_readdatavalid
	wire         mm_interconnect_0_sdram_s1_write;                              // mm_interconnect_0:SDRAM_s1_write -> SDRAM:az_wr_n
	wire  [15:0] mm_interconnect_0_sdram_s1_writedata;                          // mm_interconnect_0:SDRAM_s1_writedata -> SDRAM:az_data
	wire  [31:0] mm_interconnect_0_niosv_freertos_timer_sw_agent_readdata;      // NiosV_FreeRTOS:timer_sw_agent_readdata -> mm_interconnect_0:NiosV_FreeRTOS_timer_sw_agent_readdata
	wire         mm_interconnect_0_niosv_freertos_timer_sw_agent_waitrequest;   // NiosV_FreeRTOS:timer_sw_agent_waitrequest -> mm_interconnect_0:NiosV_FreeRTOS_timer_sw_agent_waitrequest
	wire   [5:0] mm_interconnect_0_niosv_freertos_timer_sw_agent_address;       // mm_interconnect_0:NiosV_FreeRTOS_timer_sw_agent_address -> NiosV_FreeRTOS:timer_sw_agent_address
	wire         mm_interconnect_0_niosv_freertos_timer_sw_agent_read;          // mm_interconnect_0:NiosV_FreeRTOS_timer_sw_agent_read -> NiosV_FreeRTOS:timer_sw_agent_read
	wire   [3:0] mm_interconnect_0_niosv_freertos_timer_sw_agent_byteenable;    // mm_interconnect_0:NiosV_FreeRTOS_timer_sw_agent_byteenable -> NiosV_FreeRTOS:timer_sw_agent_byteenable
	wire         mm_interconnect_0_niosv_freertos_timer_sw_agent_readdatavalid; // NiosV_FreeRTOS:timer_sw_agent_readdatavalid -> mm_interconnect_0:NiosV_FreeRTOS_timer_sw_agent_readdatavalid
	wire         mm_interconnect_0_niosv_freertos_timer_sw_agent_write;         // mm_interconnect_0:NiosV_FreeRTOS_timer_sw_agent_write -> NiosV_FreeRTOS:timer_sw_agent_write
	wire  [31:0] mm_interconnect_0_niosv_freertos_timer_sw_agent_writedata;     // mm_interconnect_0:NiosV_FreeRTOS_timer_sw_agent_writedata -> NiosV_FreeRTOS:timer_sw_agent_writedata
	wire         irq_mapper_receiver0_irq;                                      // DEBUG:av_irq -> irq_mapper:receiver0_irq
	wire  [15:0] niosv_freertos_platform_irq_rx_irq;                            // irq_mapper:sender_irq -> NiosV_FreeRTOS:platform_irq_rx_irq
	wire         rst_controller_reset_out_reset;                                // rst_controller:reset_out -> [BUTTONS_0:reset_n, DEBUG:rst_n, LEDs:reset_n, NiosV_FreeRTOS:reset_reset, SDRAM:reset_n, SEG7s_0:reset_n, SEG7s_1:reset_n, SEG7s_2:reset_n, SEG7s_3:reset_n, SEG7s_4:reset_n, SEG7s_5:reset_n, SWITCHES_0:reset_n, irq_mapper:reset, mm_interconnect_0:NiosV_FreeRTOS_reset_reset_bridge_in_reset_reset]

	BUTTON_IP buttons_0 (
		.address    (mm_interconnect_0_buttons_0_avalon_slave_0_address),    // avalon_slave_0.address
		.chipselect (mm_interconnect_0_buttons_0_avalon_slave_0_chipselect), //               .chipselect
		.write      (mm_interconnect_0_buttons_0_avalon_slave_0_write),      //               .write
		.read       (mm_interconnect_0_buttons_0_avalon_slave_0_read),       //               .read
		.writedata  (mm_interconnect_0_buttons_0_avalon_slave_0_writedata),  //               .writedata
		.readdata   (mm_interconnect_0_buttons_0_avalon_slave_0_readdata),   //               .readdata
		.clk        (clocks_sys_clk_clk),                                    //          clock.clk
		.reset_n    (~rst_controller_reset_out_reset),                       //          reset.reset_n
		.button_in  (buttons_buttons)                                        //    conduit_end.buttons
	);

	Midterm_CLOCKS clocks (
		.ref_clk_clk        (clk_clk),                            //      ref_clk.clk
		.ref_reset_reset    (niosv_freertos_dbg_reset_out_reset), //    ref_reset.reset
		.sys_clk_clk        (clocks_sys_clk_clk),                 //      sys_clk.clk
		.sdram_clk_clk      (sdram_clk_clk),                      //    sdram_clk.clk
		.reset_source_reset ()                                    // reset_source.reset
	);

	Midterm_DEBUG debug (
		.clk            (clocks_sys_clk_clk),                                    //               clk.clk
		.rst_n          (~rst_controller_reset_out_reset),                       //             reset.reset_n
		.av_chipselect  (mm_interconnect_0_debug_avalon_jtag_slave_chipselect),  // avalon_jtag_slave.chipselect
		.av_address     (mm_interconnect_0_debug_avalon_jtag_slave_address),     //                  .address
		.av_read_n      (~mm_interconnect_0_debug_avalon_jtag_slave_read),       //                  .read_n
		.av_readdata    (mm_interconnect_0_debug_avalon_jtag_slave_readdata),    //                  .readdata
		.av_write_n     (~mm_interconnect_0_debug_avalon_jtag_slave_write),      //                  .write_n
		.av_writedata   (mm_interconnect_0_debug_avalon_jtag_slave_writedata),   //                  .writedata
		.av_waitrequest (mm_interconnect_0_debug_avalon_jtag_slave_waitrequest), //                  .waitrequest
		.av_irq         (irq_mapper_receiver0_irq)                               //               irq.irq
	);

	LED_IP leds (
		.clk        (clocks_sys_clk_clk),                                 //            clock.clk
		.reset_n    (~rst_controller_reset_out_reset),                    //            reset.reset_n
		.led_out    (leds_leds),                                          //      conduit_end.leds
		.address    (mm_interconnect_0_leds_avalon_slave_0_1_address),    // avalon_slave_0_1.address
		.chipselect (mm_interconnect_0_leds_avalon_slave_0_1_chipselect), //                 .chipselect
		.write      (mm_interconnect_0_leds_avalon_slave_0_1_write),      //                 .write
		.read       (mm_interconnect_0_leds_avalon_slave_0_1_read),       //                 .read
		.writedata  (mm_interconnect_0_leds_avalon_slave_0_1_writedata),  //                 .writedata
		.readdata   (mm_interconnect_0_leds_avalon_slave_0_1_readdata)    //                 .readdata
	);

	Midterm_NiosV_FreeRTOS niosv_freertos (
		.clk                          (clocks_sys_clk_clk),                                            //                 clk.clk
		.reset_reset                  (rst_controller_reset_out_reset),                                //               reset.reset
		.platform_irq_rx_irq          (niosv_freertos_platform_irq_rx_irq),                            //     platform_irq_rx.irq
		.ndm_reset_in_reset           (niosv_freertos_dbg_reset_out_reset),                            //        ndm_reset_in.reset
		.timer_sw_agent_write         (mm_interconnect_0_niosv_freertos_timer_sw_agent_write),         //      timer_sw_agent.write
		.timer_sw_agent_writedata     (mm_interconnect_0_niosv_freertos_timer_sw_agent_writedata),     //                    .writedata
		.timer_sw_agent_byteenable    (mm_interconnect_0_niosv_freertos_timer_sw_agent_byteenable),    //                    .byteenable
		.timer_sw_agent_address       (mm_interconnect_0_niosv_freertos_timer_sw_agent_address),       //                    .address
		.timer_sw_agent_read          (mm_interconnect_0_niosv_freertos_timer_sw_agent_read),          //                    .read
		.timer_sw_agent_readdata      (mm_interconnect_0_niosv_freertos_timer_sw_agent_readdata),      //                    .readdata
		.timer_sw_agent_readdatavalid (mm_interconnect_0_niosv_freertos_timer_sw_agent_readdatavalid), //                    .readdatavalid
		.timer_sw_agent_waitrequest   (mm_interconnect_0_niosv_freertos_timer_sw_agent_waitrequest),   //                    .waitrequest
		.instruction_manager_awaddr   (niosv_freertos_instruction_manager_awaddr),                     // instruction_manager.awaddr
		.instruction_manager_awprot   (niosv_freertos_instruction_manager_awprot),                     //                    .awprot
		.instruction_manager_awvalid  (niosv_freertos_instruction_manager_awvalid),                    //                    .awvalid
		.instruction_manager_awready  (niosv_freertos_instruction_manager_awready),                    //                    .awready
		.instruction_manager_wdata    (niosv_freertos_instruction_manager_wdata),                      //                    .wdata
		.instruction_manager_wstrb    (niosv_freertos_instruction_manager_wstrb),                      //                    .wstrb
		.instruction_manager_wvalid   (niosv_freertos_instruction_manager_wvalid),                     //                    .wvalid
		.instruction_manager_wready   (niosv_freertos_instruction_manager_wready),                     //                    .wready
		.instruction_manager_bresp    (niosv_freertos_instruction_manager_bresp),                      //                    .bresp
		.instruction_manager_bvalid   (niosv_freertos_instruction_manager_bvalid),                     //                    .bvalid
		.instruction_manager_bready   (niosv_freertos_instruction_manager_bready),                     //                    .bready
		.instruction_manager_araddr   (niosv_freertos_instruction_manager_araddr),                     //                    .araddr
		.instruction_manager_arprot   (niosv_freertos_instruction_manager_arprot),                     //                    .arprot
		.instruction_manager_arvalid  (niosv_freertos_instruction_manager_arvalid),                    //                    .arvalid
		.instruction_manager_arready  (niosv_freertos_instruction_manager_arready),                    //                    .arready
		.instruction_manager_rdata    (niosv_freertos_instruction_manager_rdata),                      //                    .rdata
		.instruction_manager_rresp    (niosv_freertos_instruction_manager_rresp),                      //                    .rresp
		.instruction_manager_rvalid   (niosv_freertos_instruction_manager_rvalid),                     //                    .rvalid
		.instruction_manager_rready   (niosv_freertos_instruction_manager_rready),                     //                    .rready
		.data_manager_awaddr          (niosv_freertos_data_manager_awaddr),                            //        data_manager.awaddr
		.data_manager_awprot          (niosv_freertos_data_manager_awprot),                            //                    .awprot
		.data_manager_awvalid         (niosv_freertos_data_manager_awvalid),                           //                    .awvalid
		.data_manager_awready         (niosv_freertos_data_manager_awready),                           //                    .awready
		.data_manager_wdata           (niosv_freertos_data_manager_wdata),                             //                    .wdata
		.data_manager_wstrb           (niosv_freertos_data_manager_wstrb),                             //                    .wstrb
		.data_manager_wvalid          (niosv_freertos_data_manager_wvalid),                            //                    .wvalid
		.data_manager_wready          (niosv_freertos_data_manager_wready),                            //                    .wready
		.data_manager_bresp           (niosv_freertos_data_manager_bresp),                             //                    .bresp
		.data_manager_bvalid          (niosv_freertos_data_manager_bvalid),                            //                    .bvalid
		.data_manager_bready          (niosv_freertos_data_manager_bready),                            //                    .bready
		.data_manager_araddr          (niosv_freertos_data_manager_araddr),                            //                    .araddr
		.data_manager_arprot          (niosv_freertos_data_manager_arprot),                            //                    .arprot
		.data_manager_arvalid         (niosv_freertos_data_manager_arvalid),                           //                    .arvalid
		.data_manager_arready         (niosv_freertos_data_manager_arready),                           //                    .arready
		.data_manager_rdata           (niosv_freertos_data_manager_rdata),                             //                    .rdata
		.data_manager_rresp           (niosv_freertos_data_manager_rresp),                             //                    .rresp
		.data_manager_rvalid          (niosv_freertos_data_manager_rvalid),                            //                    .rvalid
		.data_manager_rready          (niosv_freertos_data_manager_rready),                            //                    .rready
		.dm_agent_write               (mm_interconnect_0_niosv_freertos_dm_agent_write),               //            dm_agent.write
		.dm_agent_writedata           (mm_interconnect_0_niosv_freertos_dm_agent_writedata),           //                    .writedata
		.dm_agent_address             (mm_interconnect_0_niosv_freertos_dm_agent_address),             //                    .address
		.dm_agent_read                (mm_interconnect_0_niosv_freertos_dm_agent_read),                //                    .read
		.dm_agent_readdata            (mm_interconnect_0_niosv_freertos_dm_agent_readdata),            //                    .readdata
		.dm_agent_readdatavalid       (mm_interconnect_0_niosv_freertos_dm_agent_readdatavalid),       //                    .readdatavalid
		.dm_agent_waitrequest         (mm_interconnect_0_niosv_freertos_dm_agent_waitrequest),         //                    .waitrequest
		.dbg_reset_out_reset          (niosv_freertos_dbg_reset_out_reset)                             //       dbg_reset_out.reset
	);

	Midterm_SDRAM sdram (
		.clk            (clocks_sys_clk_clk),                       //   clk.clk
		.reset_n        (~rst_controller_reset_out_reset),          // reset.reset_n
		.az_addr        (mm_interconnect_0_sdram_s1_address),       //    s1.address
		.az_be_n        (~mm_interconnect_0_sdram_s1_byteenable),   //      .byteenable_n
		.az_cs          (mm_interconnect_0_sdram_s1_chipselect),    //      .chipselect
		.az_data        (mm_interconnect_0_sdram_s1_writedata),     //      .writedata
		.az_rd_n        (~mm_interconnect_0_sdram_s1_read),         //      .read_n
		.az_wr_n        (~mm_interconnect_0_sdram_s1_write),        //      .write_n
		.za_data        (mm_interconnect_0_sdram_s1_readdata),      //      .readdata
		.za_valid       (mm_interconnect_0_sdram_s1_readdatavalid), //      .readdatavalid
		.za_waitrequest (mm_interconnect_0_sdram_s1_waitrequest),   //      .waitrequest
		.zs_addr        (sdram_wire_addr),                          //  wire.export
		.zs_ba          (sdram_wire_ba),                            //      .export
		.zs_cas_n       (sdram_wire_cas_n),                         //      .export
		.zs_cke         (sdram_wire_cke),                           //      .export
		.zs_cs_n        (sdram_wire_cs_n),                          //      .export
		.zs_dq          (sdram_wire_dq),                            //      .export
		.zs_dqm         (sdram_wire_dqm),                           //      .export
		.zs_ras_n       (sdram_wire_ras_n),                         //      .export
		.zs_we_n        (sdram_wire_we_n)                           //      .export
	);

	SEG7_IP seg7s_0 (
		.address    (mm_interconnect_0_seg7s_0_avalon_slave_0_address),    // avalon_slave_0.address
		.chipselect (mm_interconnect_0_seg7s_0_avalon_slave_0_chipselect), //               .chipselect
		.write      (mm_interconnect_0_seg7s_0_avalon_slave_0_write),      //               .write
		.read       (mm_interconnect_0_seg7s_0_avalon_slave_0_read),       //               .read
		.writedata  (mm_interconnect_0_seg7s_0_avalon_slave_0_writedata),  //               .writedata
		.readdata   (mm_interconnect_0_seg7s_0_avalon_slave_0_readdata),   //               .readdata
		.clk        (clocks_sys_clk_clk),                                  //          clock.clk
		.reset_n    (~rst_controller_reset_out_reset),                     //          reset.reset_n
		.seg_out    (hex0_segs)                                            //    conduit_end.segs
	);

	SEG7_IP seg7s_1 (
		.address    (mm_interconnect_0_seg7s_1_avalon_slave_0_address),    // avalon_slave_0.address
		.chipselect (mm_interconnect_0_seg7s_1_avalon_slave_0_chipselect), //               .chipselect
		.write      (mm_interconnect_0_seg7s_1_avalon_slave_0_write),      //               .write
		.read       (mm_interconnect_0_seg7s_1_avalon_slave_0_read),       //               .read
		.writedata  (mm_interconnect_0_seg7s_1_avalon_slave_0_writedata),  //               .writedata
		.readdata   (mm_interconnect_0_seg7s_1_avalon_slave_0_readdata),   //               .readdata
		.clk        (clocks_sys_clk_clk),                                  //          clock.clk
		.reset_n    (~rst_controller_reset_out_reset),                     //          reset.reset_n
		.seg_out    (hex1_segs)                                            //    conduit_end.segs
	);

	SEG7_IP seg7s_2 (
		.address    (mm_interconnect_0_seg7s_2_avalon_slave_0_address),    // avalon_slave_0.address
		.chipselect (mm_interconnect_0_seg7s_2_avalon_slave_0_chipselect), //               .chipselect
		.write      (mm_interconnect_0_seg7s_2_avalon_slave_0_write),      //               .write
		.read       (mm_interconnect_0_seg7s_2_avalon_slave_0_read),       //               .read
		.writedata  (mm_interconnect_0_seg7s_2_avalon_slave_0_writedata),  //               .writedata
		.readdata   (mm_interconnect_0_seg7s_2_avalon_slave_0_readdata),   //               .readdata
		.clk        (clocks_sys_clk_clk),                                  //          clock.clk
		.reset_n    (~rst_controller_reset_out_reset),                     //          reset.reset_n
		.seg_out    (hex2_segs)                                            //    conduit_end.segs
	);

	SEG7_IP seg7s_3 (
		.address    (mm_interconnect_0_seg7s_3_avalon_slave_0_address),    // avalon_slave_0.address
		.chipselect (mm_interconnect_0_seg7s_3_avalon_slave_0_chipselect), //               .chipselect
		.write      (mm_interconnect_0_seg7s_3_avalon_slave_0_write),      //               .write
		.read       (mm_interconnect_0_seg7s_3_avalon_slave_0_read),       //               .read
		.writedata  (mm_interconnect_0_seg7s_3_avalon_slave_0_writedata),  //               .writedata
		.readdata   (mm_interconnect_0_seg7s_3_avalon_slave_0_readdata),   //               .readdata
		.clk        (clocks_sys_clk_clk),                                  //          clock.clk
		.reset_n    (~rst_controller_reset_out_reset),                     //          reset.reset_n
		.seg_out    (hex3_segs)                                            //    conduit_end.segs
	);

	SEG7_IP seg7s_4 (
		.address    (mm_interconnect_0_seg7s_4_avalon_slave_0_address),    // avalon_slave_0.address
		.chipselect (mm_interconnect_0_seg7s_4_avalon_slave_0_chipselect), //               .chipselect
		.write      (mm_interconnect_0_seg7s_4_avalon_slave_0_write),      //               .write
		.read       (mm_interconnect_0_seg7s_4_avalon_slave_0_read),       //               .read
		.writedata  (mm_interconnect_0_seg7s_4_avalon_slave_0_writedata),  //               .writedata
		.readdata   (mm_interconnect_0_seg7s_4_avalon_slave_0_readdata),   //               .readdata
		.clk        (clocks_sys_clk_clk),                                  //          clock.clk
		.reset_n    (~rst_controller_reset_out_reset),                     //          reset.reset_n
		.seg_out    (hex4_segs)                                            //    conduit_end.segs
	);

	SEG7_IP seg7s_5 (
		.address    (mm_interconnect_0_seg7s_5_avalon_slave_0_address),    // avalon_slave_0.address
		.chipselect (mm_interconnect_0_seg7s_5_avalon_slave_0_chipselect), //               .chipselect
		.write      (mm_interconnect_0_seg7s_5_avalon_slave_0_write),      //               .write
		.read       (mm_interconnect_0_seg7s_5_avalon_slave_0_read),       //               .read
		.writedata  (mm_interconnect_0_seg7s_5_avalon_slave_0_writedata),  //               .writedata
		.readdata   (mm_interconnect_0_seg7s_5_avalon_slave_0_readdata),   //               .readdata
		.clk        (clocks_sys_clk_clk),                                  //          clock.clk
		.reset_n    (~rst_controller_reset_out_reset),                     //          reset.reset_n
		.seg_out    (hex5_segs)                                            //    conduit_end.segs
	);

	SW_IP switches_0 (
		.address    (mm_interconnect_0_switches_0_avalon_slave_0_address),    // avalon_slave_0.address
		.chipselect (mm_interconnect_0_switches_0_avalon_slave_0_chipselect), //               .chipselect
		.read       (mm_interconnect_0_switches_0_avalon_slave_0_read),       //               .read
		.write      (mm_interconnect_0_switches_0_avalon_slave_0_write),      //               .write
		.writedata  (mm_interconnect_0_switches_0_avalon_slave_0_writedata),  //               .writedata
		.readdata   (mm_interconnect_0_switches_0_avalon_slave_0_readdata),   //               .readdata
		.clk        (clocks_sys_clk_clk),                                     //          clock.clk
		.reset_n    (~rst_controller_reset_out_reset),                        //          reset.reset_n
		.SW         (switches_switches)                                       //    conduit_end.switches
	);

	Midterm_mm_interconnect_0 mm_interconnect_0 (
		.NiosV_FreeRTOS_data_manager_awaddr               (niosv_freertos_data_manager_awaddr),                            //                NiosV_FreeRTOS_data_manager.awaddr
		.NiosV_FreeRTOS_data_manager_awprot               (niosv_freertos_data_manager_awprot),                            //                                           .awprot
		.NiosV_FreeRTOS_data_manager_awvalid              (niosv_freertos_data_manager_awvalid),                           //                                           .awvalid
		.NiosV_FreeRTOS_data_manager_awready              (niosv_freertos_data_manager_awready),                           //                                           .awready
		.NiosV_FreeRTOS_data_manager_wdata                (niosv_freertos_data_manager_wdata),                             //                                           .wdata
		.NiosV_FreeRTOS_data_manager_wstrb                (niosv_freertos_data_manager_wstrb),                             //                                           .wstrb
		.NiosV_FreeRTOS_data_manager_wvalid               (niosv_freertos_data_manager_wvalid),                            //                                           .wvalid
		.NiosV_FreeRTOS_data_manager_wready               (niosv_freertos_data_manager_wready),                            //                                           .wready
		.NiosV_FreeRTOS_data_manager_bresp                (niosv_freertos_data_manager_bresp),                             //                                           .bresp
		.NiosV_FreeRTOS_data_manager_bvalid               (niosv_freertos_data_manager_bvalid),                            //                                           .bvalid
		.NiosV_FreeRTOS_data_manager_bready               (niosv_freertos_data_manager_bready),                            //                                           .bready
		.NiosV_FreeRTOS_data_manager_araddr               (niosv_freertos_data_manager_araddr),                            //                                           .araddr
		.NiosV_FreeRTOS_data_manager_arprot               (niosv_freertos_data_manager_arprot),                            //                                           .arprot
		.NiosV_FreeRTOS_data_manager_arvalid              (niosv_freertos_data_manager_arvalid),                           //                                           .arvalid
		.NiosV_FreeRTOS_data_manager_arready              (niosv_freertos_data_manager_arready),                           //                                           .arready
		.NiosV_FreeRTOS_data_manager_rdata                (niosv_freertos_data_manager_rdata),                             //                                           .rdata
		.NiosV_FreeRTOS_data_manager_rresp                (niosv_freertos_data_manager_rresp),                             //                                           .rresp
		.NiosV_FreeRTOS_data_manager_rvalid               (niosv_freertos_data_manager_rvalid),                            //                                           .rvalid
		.NiosV_FreeRTOS_data_manager_rready               (niosv_freertos_data_manager_rready),                            //                                           .rready
		.NiosV_FreeRTOS_instruction_manager_awaddr        (niosv_freertos_instruction_manager_awaddr),                     //         NiosV_FreeRTOS_instruction_manager.awaddr
		.NiosV_FreeRTOS_instruction_manager_awprot        (niosv_freertos_instruction_manager_awprot),                     //                                           .awprot
		.NiosV_FreeRTOS_instruction_manager_awvalid       (niosv_freertos_instruction_manager_awvalid),                    //                                           .awvalid
		.NiosV_FreeRTOS_instruction_manager_awready       (niosv_freertos_instruction_manager_awready),                    //                                           .awready
		.NiosV_FreeRTOS_instruction_manager_wdata         (niosv_freertos_instruction_manager_wdata),                      //                                           .wdata
		.NiosV_FreeRTOS_instruction_manager_wstrb         (niosv_freertos_instruction_manager_wstrb),                      //                                           .wstrb
		.NiosV_FreeRTOS_instruction_manager_wvalid        (niosv_freertos_instruction_manager_wvalid),                     //                                           .wvalid
		.NiosV_FreeRTOS_instruction_manager_wready        (niosv_freertos_instruction_manager_wready),                     //                                           .wready
		.NiosV_FreeRTOS_instruction_manager_bresp         (niosv_freertos_instruction_manager_bresp),                      //                                           .bresp
		.NiosV_FreeRTOS_instruction_manager_bvalid        (niosv_freertos_instruction_manager_bvalid),                     //                                           .bvalid
		.NiosV_FreeRTOS_instruction_manager_bready        (niosv_freertos_instruction_manager_bready),                     //                                           .bready
		.NiosV_FreeRTOS_instruction_manager_araddr        (niosv_freertos_instruction_manager_araddr),                     //                                           .araddr
		.NiosV_FreeRTOS_instruction_manager_arprot        (niosv_freertos_instruction_manager_arprot),                     //                                           .arprot
		.NiosV_FreeRTOS_instruction_manager_arvalid       (niosv_freertos_instruction_manager_arvalid),                    //                                           .arvalid
		.NiosV_FreeRTOS_instruction_manager_arready       (niosv_freertos_instruction_manager_arready),                    //                                           .arready
		.NiosV_FreeRTOS_instruction_manager_rdata         (niosv_freertos_instruction_manager_rdata),                      //                                           .rdata
		.NiosV_FreeRTOS_instruction_manager_rresp         (niosv_freertos_instruction_manager_rresp),                      //                                           .rresp
		.NiosV_FreeRTOS_instruction_manager_rvalid        (niosv_freertos_instruction_manager_rvalid),                     //                                           .rvalid
		.NiosV_FreeRTOS_instruction_manager_rready        (niosv_freertos_instruction_manager_rready),                     //                                           .rready
		.CLOCKS_sys_clk_clk                               (clocks_sys_clk_clk),                                            //                             CLOCKS_sys_clk.clk
		.NiosV_FreeRTOS_reset_reset_bridge_in_reset_reset (rst_controller_reset_out_reset),                                // NiosV_FreeRTOS_reset_reset_bridge_in_reset.reset
		.BUTTONS_0_avalon_slave_0_address                 (mm_interconnect_0_buttons_0_avalon_slave_0_address),            //                   BUTTONS_0_avalon_slave_0.address
		.BUTTONS_0_avalon_slave_0_write                   (mm_interconnect_0_buttons_0_avalon_slave_0_write),              //                                           .write
		.BUTTONS_0_avalon_slave_0_read                    (mm_interconnect_0_buttons_0_avalon_slave_0_read),               //                                           .read
		.BUTTONS_0_avalon_slave_0_readdata                (mm_interconnect_0_buttons_0_avalon_slave_0_readdata),           //                                           .readdata
		.BUTTONS_0_avalon_slave_0_writedata               (mm_interconnect_0_buttons_0_avalon_slave_0_writedata),          //                                           .writedata
		.BUTTONS_0_avalon_slave_0_chipselect              (mm_interconnect_0_buttons_0_avalon_slave_0_chipselect),         //                                           .chipselect
		.DEBUG_avalon_jtag_slave_address                  (mm_interconnect_0_debug_avalon_jtag_slave_address),             //                    DEBUG_avalon_jtag_slave.address
		.DEBUG_avalon_jtag_slave_write                    (mm_interconnect_0_debug_avalon_jtag_slave_write),               //                                           .write
		.DEBUG_avalon_jtag_slave_read                     (mm_interconnect_0_debug_avalon_jtag_slave_read),                //                                           .read
		.DEBUG_avalon_jtag_slave_readdata                 (mm_interconnect_0_debug_avalon_jtag_slave_readdata),            //                                           .readdata
		.DEBUG_avalon_jtag_slave_writedata                (mm_interconnect_0_debug_avalon_jtag_slave_writedata),           //                                           .writedata
		.DEBUG_avalon_jtag_slave_waitrequest              (mm_interconnect_0_debug_avalon_jtag_slave_waitrequest),         //                                           .waitrequest
		.DEBUG_avalon_jtag_slave_chipselect               (mm_interconnect_0_debug_avalon_jtag_slave_chipselect),          //                                           .chipselect
		.LEDs_avalon_slave_0_1_address                    (mm_interconnect_0_leds_avalon_slave_0_1_address),               //                      LEDs_avalon_slave_0_1.address
		.LEDs_avalon_slave_0_1_write                      (mm_interconnect_0_leds_avalon_slave_0_1_write),                 //                                           .write
		.LEDs_avalon_slave_0_1_read                       (mm_interconnect_0_leds_avalon_slave_0_1_read),                  //                                           .read
		.LEDs_avalon_slave_0_1_readdata                   (mm_interconnect_0_leds_avalon_slave_0_1_readdata),              //                                           .readdata
		.LEDs_avalon_slave_0_1_writedata                  (mm_interconnect_0_leds_avalon_slave_0_1_writedata),             //                                           .writedata
		.LEDs_avalon_slave_0_1_chipselect                 (mm_interconnect_0_leds_avalon_slave_0_1_chipselect),            //                                           .chipselect
		.NiosV_FreeRTOS_dm_agent_address                  (mm_interconnect_0_niosv_freertos_dm_agent_address),             //                    NiosV_FreeRTOS_dm_agent.address
		.NiosV_FreeRTOS_dm_agent_write                    (mm_interconnect_0_niosv_freertos_dm_agent_write),               //                                           .write
		.NiosV_FreeRTOS_dm_agent_read                     (mm_interconnect_0_niosv_freertos_dm_agent_read),                //                                           .read
		.NiosV_FreeRTOS_dm_agent_readdata                 (mm_interconnect_0_niosv_freertos_dm_agent_readdata),            //                                           .readdata
		.NiosV_FreeRTOS_dm_agent_writedata                (mm_interconnect_0_niosv_freertos_dm_agent_writedata),           //                                           .writedata
		.NiosV_FreeRTOS_dm_agent_readdatavalid            (mm_interconnect_0_niosv_freertos_dm_agent_readdatavalid),       //                                           .readdatavalid
		.NiosV_FreeRTOS_dm_agent_waitrequest              (mm_interconnect_0_niosv_freertos_dm_agent_waitrequest),         //                                           .waitrequest
		.NiosV_FreeRTOS_timer_sw_agent_address            (mm_interconnect_0_niosv_freertos_timer_sw_agent_address),       //              NiosV_FreeRTOS_timer_sw_agent.address
		.NiosV_FreeRTOS_timer_sw_agent_write              (mm_interconnect_0_niosv_freertos_timer_sw_agent_write),         //                                           .write
		.NiosV_FreeRTOS_timer_sw_agent_read               (mm_interconnect_0_niosv_freertos_timer_sw_agent_read),          //                                           .read
		.NiosV_FreeRTOS_timer_sw_agent_readdata           (mm_interconnect_0_niosv_freertos_timer_sw_agent_readdata),      //                                           .readdata
		.NiosV_FreeRTOS_timer_sw_agent_writedata          (mm_interconnect_0_niosv_freertos_timer_sw_agent_writedata),     //                                           .writedata
		.NiosV_FreeRTOS_timer_sw_agent_byteenable         (mm_interconnect_0_niosv_freertos_timer_sw_agent_byteenable),    //                                           .byteenable
		.NiosV_FreeRTOS_timer_sw_agent_readdatavalid      (mm_interconnect_0_niosv_freertos_timer_sw_agent_readdatavalid), //                                           .readdatavalid
		.NiosV_FreeRTOS_timer_sw_agent_waitrequest        (mm_interconnect_0_niosv_freertos_timer_sw_agent_waitrequest),   //                                           .waitrequest
		.SDRAM_s1_address                                 (mm_interconnect_0_sdram_s1_address),                            //                                   SDRAM_s1.address
		.SDRAM_s1_write                                   (mm_interconnect_0_sdram_s1_write),                              //                                           .write
		.SDRAM_s1_read                                    (mm_interconnect_0_sdram_s1_read),                               //                                           .read
		.SDRAM_s1_readdata                                (mm_interconnect_0_sdram_s1_readdata),                           //                                           .readdata
		.SDRAM_s1_writedata                               (mm_interconnect_0_sdram_s1_writedata),                          //                                           .writedata
		.SDRAM_s1_byteenable                              (mm_interconnect_0_sdram_s1_byteenable),                         //                                           .byteenable
		.SDRAM_s1_readdatavalid                           (mm_interconnect_0_sdram_s1_readdatavalid),                      //                                           .readdatavalid
		.SDRAM_s1_waitrequest                             (mm_interconnect_0_sdram_s1_waitrequest),                        //                                           .waitrequest
		.SDRAM_s1_chipselect                              (mm_interconnect_0_sdram_s1_chipselect),                         //                                           .chipselect
		.SEG7s_0_avalon_slave_0_address                   (mm_interconnect_0_seg7s_0_avalon_slave_0_address),              //                     SEG7s_0_avalon_slave_0.address
		.SEG7s_0_avalon_slave_0_write                     (mm_interconnect_0_seg7s_0_avalon_slave_0_write),                //                                           .write
		.SEG7s_0_avalon_slave_0_read                      (mm_interconnect_0_seg7s_0_avalon_slave_0_read),                 //                                           .read
		.SEG7s_0_avalon_slave_0_readdata                  (mm_interconnect_0_seg7s_0_avalon_slave_0_readdata),             //                                           .readdata
		.SEG7s_0_avalon_slave_0_writedata                 (mm_interconnect_0_seg7s_0_avalon_slave_0_writedata),            //                                           .writedata
		.SEG7s_0_avalon_slave_0_chipselect                (mm_interconnect_0_seg7s_0_avalon_slave_0_chipselect),           //                                           .chipselect
		.SEG7s_1_avalon_slave_0_address                   (mm_interconnect_0_seg7s_1_avalon_slave_0_address),              //                     SEG7s_1_avalon_slave_0.address
		.SEG7s_1_avalon_slave_0_write                     (mm_interconnect_0_seg7s_1_avalon_slave_0_write),                //                                           .write
		.SEG7s_1_avalon_slave_0_read                      (mm_interconnect_0_seg7s_1_avalon_slave_0_read),                 //                                           .read
		.SEG7s_1_avalon_slave_0_readdata                  (mm_interconnect_0_seg7s_1_avalon_slave_0_readdata),             //                                           .readdata
		.SEG7s_1_avalon_slave_0_writedata                 (mm_interconnect_0_seg7s_1_avalon_slave_0_writedata),            //                                           .writedata
		.SEG7s_1_avalon_slave_0_chipselect                (mm_interconnect_0_seg7s_1_avalon_slave_0_chipselect),           //                                           .chipselect
		.SEG7s_2_avalon_slave_0_address                   (mm_interconnect_0_seg7s_2_avalon_slave_0_address),              //                     SEG7s_2_avalon_slave_0.address
		.SEG7s_2_avalon_slave_0_write                     (mm_interconnect_0_seg7s_2_avalon_slave_0_write),                //                                           .write
		.SEG7s_2_avalon_slave_0_read                      (mm_interconnect_0_seg7s_2_avalon_slave_0_read),                 //                                           .read
		.SEG7s_2_avalon_slave_0_readdata                  (mm_interconnect_0_seg7s_2_avalon_slave_0_readdata),             //                                           .readdata
		.SEG7s_2_avalon_slave_0_writedata                 (mm_interconnect_0_seg7s_2_avalon_slave_0_writedata),            //                                           .writedata
		.SEG7s_2_avalon_slave_0_chipselect                (mm_interconnect_0_seg7s_2_avalon_slave_0_chipselect),           //                                           .chipselect
		.SEG7s_3_avalon_slave_0_address                   (mm_interconnect_0_seg7s_3_avalon_slave_0_address),              //                     SEG7s_3_avalon_slave_0.address
		.SEG7s_3_avalon_slave_0_write                     (mm_interconnect_0_seg7s_3_avalon_slave_0_write),                //                                           .write
		.SEG7s_3_avalon_slave_0_read                      (mm_interconnect_0_seg7s_3_avalon_slave_0_read),                 //                                           .read
		.SEG7s_3_avalon_slave_0_readdata                  (mm_interconnect_0_seg7s_3_avalon_slave_0_readdata),             //                                           .readdata
		.SEG7s_3_avalon_slave_0_writedata                 (mm_interconnect_0_seg7s_3_avalon_slave_0_writedata),            //                                           .writedata
		.SEG7s_3_avalon_slave_0_chipselect                (mm_interconnect_0_seg7s_3_avalon_slave_0_chipselect),           //                                           .chipselect
		.SEG7s_4_avalon_slave_0_address                   (mm_interconnect_0_seg7s_4_avalon_slave_0_address),              //                     SEG7s_4_avalon_slave_0.address
		.SEG7s_4_avalon_slave_0_write                     (mm_interconnect_0_seg7s_4_avalon_slave_0_write),                //                                           .write
		.SEG7s_4_avalon_slave_0_read                      (mm_interconnect_0_seg7s_4_avalon_slave_0_read),                 //                                           .read
		.SEG7s_4_avalon_slave_0_readdata                  (mm_interconnect_0_seg7s_4_avalon_slave_0_readdata),             //                                           .readdata
		.SEG7s_4_avalon_slave_0_writedata                 (mm_interconnect_0_seg7s_4_avalon_slave_0_writedata),            //                                           .writedata
		.SEG7s_4_avalon_slave_0_chipselect                (mm_interconnect_0_seg7s_4_avalon_slave_0_chipselect),           //                                           .chipselect
		.SEG7s_5_avalon_slave_0_address                   (mm_interconnect_0_seg7s_5_avalon_slave_0_address),              //                     SEG7s_5_avalon_slave_0.address
		.SEG7s_5_avalon_slave_0_write                     (mm_interconnect_0_seg7s_5_avalon_slave_0_write),                //                                           .write
		.SEG7s_5_avalon_slave_0_read                      (mm_interconnect_0_seg7s_5_avalon_slave_0_read),                 //                                           .read
		.SEG7s_5_avalon_slave_0_readdata                  (mm_interconnect_0_seg7s_5_avalon_slave_0_readdata),             //                                           .readdata
		.SEG7s_5_avalon_slave_0_writedata                 (mm_interconnect_0_seg7s_5_avalon_slave_0_writedata),            //                                           .writedata
		.SEG7s_5_avalon_slave_0_chipselect                (mm_interconnect_0_seg7s_5_avalon_slave_0_chipselect),           //                                           .chipselect
		.SWITCHES_0_avalon_slave_0_address                (mm_interconnect_0_switches_0_avalon_slave_0_address),           //                  SWITCHES_0_avalon_slave_0.address
		.SWITCHES_0_avalon_slave_0_write                  (mm_interconnect_0_switches_0_avalon_slave_0_write),             //                                           .write
		.SWITCHES_0_avalon_slave_0_read                   (mm_interconnect_0_switches_0_avalon_slave_0_read),              //                                           .read
		.SWITCHES_0_avalon_slave_0_readdata               (mm_interconnect_0_switches_0_avalon_slave_0_readdata),          //                                           .readdata
		.SWITCHES_0_avalon_slave_0_writedata              (mm_interconnect_0_switches_0_avalon_slave_0_writedata),         //                                           .writedata
		.SWITCHES_0_avalon_slave_0_chipselect             (mm_interconnect_0_switches_0_avalon_slave_0_chipselect)         //                                           .chipselect
	);

	Midterm_irq_mapper irq_mapper (
		.clk           (clocks_sys_clk_clk),                 //       clk.clk
		.reset         (rst_controller_reset_out_reset),     // clk_reset.reset
		.receiver0_irq (irq_mapper_receiver0_irq),           // receiver0.irq
		.sender_irq    (niosv_freertos_platform_irq_rx_irq)  //    sender.irq
	);

	altera_reset_controller #(
		.NUM_RESET_INPUTS          (1),
		.OUTPUT_RESET_SYNC_EDGES   ("deassert"),
		.SYNC_DEPTH                (2),
		.RESET_REQUEST_PRESENT     (0),
		.RESET_REQ_WAIT_TIME       (1),
		.MIN_RST_ASSERTION_TIME    (3),
		.RESET_REQ_EARLY_DSRT_TIME (1),
		.USE_RESET_REQUEST_IN0     (0),
		.USE_RESET_REQUEST_IN1     (0),
		.USE_RESET_REQUEST_IN2     (0),
		.USE_RESET_REQUEST_IN3     (0),
		.USE_RESET_REQUEST_IN4     (0),
		.USE_RESET_REQUEST_IN5     (0),
		.USE_RESET_REQUEST_IN6     (0),
		.USE_RESET_REQUEST_IN7     (0),
		.USE_RESET_REQUEST_IN8     (0),
		.USE_RESET_REQUEST_IN9     (0),
		.USE_RESET_REQUEST_IN10    (0),
		.USE_RESET_REQUEST_IN11    (0),
		.USE_RESET_REQUEST_IN12    (0),
		.USE_RESET_REQUEST_IN13    (0),
		.USE_RESET_REQUEST_IN14    (0),
		.USE_RESET_REQUEST_IN15    (0),
		.ADAPT_RESET_REQUEST       (0)
	) rst_controller (
		.reset_in0      (niosv_freertos_dbg_reset_out_reset), // reset_in0.reset
		.clk            (clocks_sys_clk_clk),                 //       clk.clk
		.reset_out      (rst_controller_reset_out_reset),     // reset_out.reset
		.reset_req      (),                                   // (terminated)
		.reset_req_in0  (1'b0),                               // (terminated)
		.reset_in1      (1'b0),                               // (terminated)
		.reset_req_in1  (1'b0),                               // (terminated)
		.reset_in2      (1'b0),                               // (terminated)
		.reset_req_in2  (1'b0),                               // (terminated)
		.reset_in3      (1'b0),                               // (terminated)
		.reset_req_in3  (1'b0),                               // (terminated)
		.reset_in4      (1'b0),                               // (terminated)
		.reset_req_in4  (1'b0),                               // (terminated)
		.reset_in5      (1'b0),                               // (terminated)
		.reset_req_in5  (1'b0),                               // (terminated)
		.reset_in6      (1'b0),                               // (terminated)
		.reset_req_in6  (1'b0),                               // (terminated)
		.reset_in7      (1'b0),                               // (terminated)
		.reset_req_in7  (1'b0),                               // (terminated)
		.reset_in8      (1'b0),                               // (terminated)
		.reset_req_in8  (1'b0),                               // (terminated)
		.reset_in9      (1'b0),                               // (terminated)
		.reset_req_in9  (1'b0),                               // (terminated)
		.reset_in10     (1'b0),                               // (terminated)
		.reset_req_in10 (1'b0),                               // (terminated)
		.reset_in11     (1'b0),                               // (terminated)
		.reset_req_in11 (1'b0),                               // (terminated)
		.reset_in12     (1'b0),                               // (terminated)
		.reset_req_in12 (1'b0),                               // (terminated)
		.reset_in13     (1'b0),                               // (terminated)
		.reset_req_in13 (1'b0),                               // (terminated)
		.reset_in14     (1'b0),                               // (terminated)
		.reset_req_in14 (1'b0),                               // (terminated)
		.reset_in15     (1'b0),                               // (terminated)
		.reset_req_in15 (1'b0)                                // (terminated)
	);

endmodule
