// Lab3.v

// Generated using ACDS version 23.1 991

`timescale 1 ps / 1 ps
module Lab3 (
		input  wire       clk_clk,     //  clk.clk
		output wire [6:0] hex0_export, // hex0.export
		output wire [6:0] hex1_export, // hex1.export
		output wire [6:0] hex2_export, // hex2.export
		output wire [6:0] hex3_export, // hex3.export
		output wire [6:0] hex4_export, // hex4.export
		output wire [6:0] hex5_export, // hex5.export
		input  wire [8:0] sw_export    //   sw.export
	);

	wire         lab3_dbg_reset_out_reset;                              // Lab3:dbg_reset_out_reset -> [Lab3:ndm_reset_in_reset, rst_controller:reset_in0, rst_controller_001:reset_in0, rst_controller_001:reset_in1]
	wire  [31:0] lab3_data_manager_awaddr;                              // Lab3:data_manager_awaddr -> mm_interconnect_0:Lab3_data_manager_awaddr
	wire   [1:0] lab3_data_manager_bresp;                               // mm_interconnect_0:Lab3_data_manager_bresp -> Lab3:data_manager_bresp
	wire         lab3_data_manager_arready;                             // mm_interconnect_0:Lab3_data_manager_arready -> Lab3:data_manager_arready
	wire  [31:0] lab3_data_manager_rdata;                               // mm_interconnect_0:Lab3_data_manager_rdata -> Lab3:data_manager_rdata
	wire   [3:0] lab3_data_manager_wstrb;                               // Lab3:data_manager_wstrb -> mm_interconnect_0:Lab3_data_manager_wstrb
	wire         lab3_data_manager_wready;                              // mm_interconnect_0:Lab3_data_manager_wready -> Lab3:data_manager_wready
	wire         lab3_data_manager_awready;                             // mm_interconnect_0:Lab3_data_manager_awready -> Lab3:data_manager_awready
	wire         lab3_data_manager_rready;                              // Lab3:data_manager_rready -> mm_interconnect_0:Lab3_data_manager_rready
	wire         lab3_data_manager_bready;                              // Lab3:data_manager_bready -> mm_interconnect_0:Lab3_data_manager_bready
	wire         lab3_data_manager_wvalid;                              // Lab3:data_manager_wvalid -> mm_interconnect_0:Lab3_data_manager_wvalid
	wire  [31:0] lab3_data_manager_araddr;                              // Lab3:data_manager_araddr -> mm_interconnect_0:Lab3_data_manager_araddr
	wire   [2:0] lab3_data_manager_arprot;                              // Lab3:data_manager_arprot -> mm_interconnect_0:Lab3_data_manager_arprot
	wire   [1:0] lab3_data_manager_rresp;                               // mm_interconnect_0:Lab3_data_manager_rresp -> Lab3:data_manager_rresp
	wire   [2:0] lab3_data_manager_awprot;                              // Lab3:data_manager_awprot -> mm_interconnect_0:Lab3_data_manager_awprot
	wire  [31:0] lab3_data_manager_wdata;                               // Lab3:data_manager_wdata -> mm_interconnect_0:Lab3_data_manager_wdata
	wire         lab3_data_manager_arvalid;                             // Lab3:data_manager_arvalid -> mm_interconnect_0:Lab3_data_manager_arvalid
	wire         lab3_data_manager_bvalid;                              // mm_interconnect_0:Lab3_data_manager_bvalid -> Lab3:data_manager_bvalid
	wire         lab3_data_manager_awvalid;                             // Lab3:data_manager_awvalid -> mm_interconnect_0:Lab3_data_manager_awvalid
	wire         lab3_data_manager_rvalid;                              // mm_interconnect_0:Lab3_data_manager_rvalid -> Lab3:data_manager_rvalid
	wire  [31:0] lab3_instruction_manager_awaddr;                       // Lab3:instruction_manager_awaddr -> mm_interconnect_0:Lab3_instruction_manager_awaddr
	wire   [1:0] lab3_instruction_manager_bresp;                        // mm_interconnect_0:Lab3_instruction_manager_bresp -> Lab3:instruction_manager_bresp
	wire         lab3_instruction_manager_arready;                      // mm_interconnect_0:Lab3_instruction_manager_arready -> Lab3:instruction_manager_arready
	wire  [31:0] lab3_instruction_manager_rdata;                        // mm_interconnect_0:Lab3_instruction_manager_rdata -> Lab3:instruction_manager_rdata
	wire   [3:0] lab3_instruction_manager_wstrb;                        // Lab3:instruction_manager_wstrb -> mm_interconnect_0:Lab3_instruction_manager_wstrb
	wire         lab3_instruction_manager_wready;                       // mm_interconnect_0:Lab3_instruction_manager_wready -> Lab3:instruction_manager_wready
	wire         lab3_instruction_manager_awready;                      // mm_interconnect_0:Lab3_instruction_manager_awready -> Lab3:instruction_manager_awready
	wire         lab3_instruction_manager_rready;                       // Lab3:instruction_manager_rready -> mm_interconnect_0:Lab3_instruction_manager_rready
	wire         lab3_instruction_manager_bready;                       // Lab3:instruction_manager_bready -> mm_interconnect_0:Lab3_instruction_manager_bready
	wire         lab3_instruction_manager_wvalid;                       // Lab3:instruction_manager_wvalid -> mm_interconnect_0:Lab3_instruction_manager_wvalid
	wire  [31:0] lab3_instruction_manager_araddr;                       // Lab3:instruction_manager_araddr -> mm_interconnect_0:Lab3_instruction_manager_araddr
	wire   [2:0] lab3_instruction_manager_arprot;                       // Lab3:instruction_manager_arprot -> mm_interconnect_0:Lab3_instruction_manager_arprot
	wire   [1:0] lab3_instruction_manager_rresp;                        // mm_interconnect_0:Lab3_instruction_manager_rresp -> Lab3:instruction_manager_rresp
	wire   [2:0] lab3_instruction_manager_awprot;                       // Lab3:instruction_manager_awprot -> mm_interconnect_0:Lab3_instruction_manager_awprot
	wire  [31:0] lab3_instruction_manager_wdata;                        // Lab3:instruction_manager_wdata -> mm_interconnect_0:Lab3_instruction_manager_wdata
	wire         lab3_instruction_manager_arvalid;                      // Lab3:instruction_manager_arvalid -> mm_interconnect_0:Lab3_instruction_manager_arvalid
	wire         lab3_instruction_manager_bvalid;                       // mm_interconnect_0:Lab3_instruction_manager_bvalid -> Lab3:instruction_manager_bvalid
	wire         lab3_instruction_manager_awvalid;                      // Lab3:instruction_manager_awvalid -> mm_interconnect_0:Lab3_instruction_manager_awvalid
	wire         lab3_instruction_manager_rvalid;                       // mm_interconnect_0:Lab3_instruction_manager_rvalid -> Lab3:instruction_manager_rvalid
	wire         mm_interconnect_0_debug_avalon_jtag_slave_chipselect;  // mm_interconnect_0:DEBUG_avalon_jtag_slave_chipselect -> DEBUG:av_chipselect
	wire  [31:0] mm_interconnect_0_debug_avalon_jtag_slave_readdata;    // DEBUG:av_readdata -> mm_interconnect_0:DEBUG_avalon_jtag_slave_readdata
	wire         mm_interconnect_0_debug_avalon_jtag_slave_waitrequest; // DEBUG:av_waitrequest -> mm_interconnect_0:DEBUG_avalon_jtag_slave_waitrequest
	wire   [0:0] mm_interconnect_0_debug_avalon_jtag_slave_address;     // mm_interconnect_0:DEBUG_avalon_jtag_slave_address -> DEBUG:av_address
	wire         mm_interconnect_0_debug_avalon_jtag_slave_read;        // mm_interconnect_0:DEBUG_avalon_jtag_slave_read -> DEBUG:av_read_n
	wire         mm_interconnect_0_debug_avalon_jtag_slave_write;       // mm_interconnect_0:DEBUG_avalon_jtag_slave_write -> DEBUG:av_write_n
	wire  [31:0] mm_interconnect_0_debug_avalon_jtag_slave_writedata;   // mm_interconnect_0:DEBUG_avalon_jtag_slave_writedata -> DEBUG:av_writedata
	wire  [31:0] mm_interconnect_0_lab3_dm_agent_readdata;              // Lab3:dm_agent_readdata -> mm_interconnect_0:Lab3_dm_agent_readdata
	wire         mm_interconnect_0_lab3_dm_agent_waitrequest;           // Lab3:dm_agent_waitrequest -> mm_interconnect_0:Lab3_dm_agent_waitrequest
	wire  [15:0] mm_interconnect_0_lab3_dm_agent_address;               // mm_interconnect_0:Lab3_dm_agent_address -> Lab3:dm_agent_address
	wire         mm_interconnect_0_lab3_dm_agent_read;                  // mm_interconnect_0:Lab3_dm_agent_read -> Lab3:dm_agent_read
	wire         mm_interconnect_0_lab3_dm_agent_readdatavalid;         // Lab3:dm_agent_readdatavalid -> mm_interconnect_0:Lab3_dm_agent_readdatavalid
	wire         mm_interconnect_0_lab3_dm_agent_write;                 // mm_interconnect_0:Lab3_dm_agent_write -> Lab3:dm_agent_write
	wire  [31:0] mm_interconnect_0_lab3_dm_agent_writedata;             // mm_interconnect_0:Lab3_dm_agent_writedata -> Lab3:dm_agent_writedata
	wire         mm_interconnect_0_sram_s1_chipselect;                  // mm_interconnect_0:SRAM_s1_chipselect -> SRAM:chipselect
	wire  [31:0] mm_interconnect_0_sram_s1_readdata;                    // SRAM:readdata -> mm_interconnect_0:SRAM_s1_readdata
	wire  [15:0] mm_interconnect_0_sram_s1_address;                     // mm_interconnect_0:SRAM_s1_address -> SRAM:address
	wire   [3:0] mm_interconnect_0_sram_s1_byteenable;                  // mm_interconnect_0:SRAM_s1_byteenable -> SRAM:byteenable
	wire         mm_interconnect_0_sram_s1_write;                       // mm_interconnect_0:SRAM_s1_write -> SRAM:write
	wire  [31:0] mm_interconnect_0_sram_s1_writedata;                   // mm_interconnect_0:SRAM_s1_writedata -> SRAM:writedata
	wire         mm_interconnect_0_sram_s1_clken;                       // mm_interconnect_0:SRAM_s1_clken -> SRAM:clken
	wire         mm_interconnect_0_hex0_s1_chipselect;                  // mm_interconnect_0:HEX0_s1_chipselect -> HEX0:chipselect
	wire  [31:0] mm_interconnect_0_hex0_s1_readdata;                    // HEX0:readdata -> mm_interconnect_0:HEX0_s1_readdata
	wire   [2:0] mm_interconnect_0_hex0_s1_address;                     // mm_interconnect_0:HEX0_s1_address -> HEX0:address
	wire         mm_interconnect_0_hex0_s1_write;                       // mm_interconnect_0:HEX0_s1_write -> HEX0:write_n
	wire  [31:0] mm_interconnect_0_hex0_s1_writedata;                   // mm_interconnect_0:HEX0_s1_writedata -> HEX0:writedata
	wire         mm_interconnect_0_hex1_s1_chipselect;                  // mm_interconnect_0:HEX1_s1_chipselect -> HEX1:chipselect
	wire  [31:0] mm_interconnect_0_hex1_s1_readdata;                    // HEX1:readdata -> mm_interconnect_0:HEX1_s1_readdata
	wire   [2:0] mm_interconnect_0_hex1_s1_address;                     // mm_interconnect_0:HEX1_s1_address -> HEX1:address
	wire         mm_interconnect_0_hex1_s1_write;                       // mm_interconnect_0:HEX1_s1_write -> HEX1:write_n
	wire  [31:0] mm_interconnect_0_hex1_s1_writedata;                   // mm_interconnect_0:HEX1_s1_writedata -> HEX1:writedata
	wire         mm_interconnect_0_hex2_s1_chipselect;                  // mm_interconnect_0:HEX2_s1_chipselect -> HEX2:chipselect
	wire  [31:0] mm_interconnect_0_hex2_s1_readdata;                    // HEX2:readdata -> mm_interconnect_0:HEX2_s1_readdata
	wire   [2:0] mm_interconnect_0_hex2_s1_address;                     // mm_interconnect_0:HEX2_s1_address -> HEX2:address
	wire         mm_interconnect_0_hex2_s1_write;                       // mm_interconnect_0:HEX2_s1_write -> HEX2:write_n
	wire  [31:0] mm_interconnect_0_hex2_s1_writedata;                   // mm_interconnect_0:HEX2_s1_writedata -> HEX2:writedata
	wire         mm_interconnect_0_hex3_s1_chipselect;                  // mm_interconnect_0:HEX3_s1_chipselect -> HEX3:chipselect
	wire  [31:0] mm_interconnect_0_hex3_s1_readdata;                    // HEX3:readdata -> mm_interconnect_0:HEX3_s1_readdata
	wire   [2:0] mm_interconnect_0_hex3_s1_address;                     // mm_interconnect_0:HEX3_s1_address -> HEX3:address
	wire         mm_interconnect_0_hex3_s1_write;                       // mm_interconnect_0:HEX3_s1_write -> HEX3:write_n
	wire  [31:0] mm_interconnect_0_hex3_s1_writedata;                   // mm_interconnect_0:HEX3_s1_writedata -> HEX3:writedata
	wire         mm_interconnect_0_hex4_s1_chipselect;                  // mm_interconnect_0:HEX4_s1_chipselect -> HEX4:chipselect
	wire  [31:0] mm_interconnect_0_hex4_s1_readdata;                    // HEX4:readdata -> mm_interconnect_0:HEX4_s1_readdata
	wire   [2:0] mm_interconnect_0_hex4_s1_address;                     // mm_interconnect_0:HEX4_s1_address -> HEX4:address
	wire         mm_interconnect_0_hex4_s1_write;                       // mm_interconnect_0:HEX4_s1_write -> HEX4:write_n
	wire  [31:0] mm_interconnect_0_hex4_s1_writedata;                   // mm_interconnect_0:HEX4_s1_writedata -> HEX4:writedata
	wire         mm_interconnect_0_hex5_s1_chipselect;                  // mm_interconnect_0:HEX5_s1_chipselect -> HEX5:chipselect
	wire  [31:0] mm_interconnect_0_hex5_s1_readdata;                    // HEX5:readdata -> mm_interconnect_0:HEX5_s1_readdata
	wire   [2:0] mm_interconnect_0_hex5_s1_address;                     // mm_interconnect_0:HEX5_s1_address -> HEX5:address
	wire         mm_interconnect_0_hex5_s1_write;                       // mm_interconnect_0:HEX5_s1_write -> HEX5:write_n
	wire  [31:0] mm_interconnect_0_hex5_s1_writedata;                   // mm_interconnect_0:HEX5_s1_writedata -> HEX5:writedata
	wire  [31:0] mm_interconnect_0_switches_s1_readdata;                // switches:readdata -> mm_interconnect_0:switches_s1_readdata
	wire   [1:0] mm_interconnect_0_switches_s1_address;                 // mm_interconnect_0:switches_s1_address -> switches:address
	wire  [31:0] mm_interconnect_0_lab3_timer_sw_agent_readdata;        // Lab3:timer_sw_agent_readdata -> mm_interconnect_0:Lab3_timer_sw_agent_readdata
	wire         mm_interconnect_0_lab3_timer_sw_agent_waitrequest;     // Lab3:timer_sw_agent_waitrequest -> mm_interconnect_0:Lab3_timer_sw_agent_waitrequest
	wire   [5:0] mm_interconnect_0_lab3_timer_sw_agent_address;         // mm_interconnect_0:Lab3_timer_sw_agent_address -> Lab3:timer_sw_agent_address
	wire         mm_interconnect_0_lab3_timer_sw_agent_read;            // mm_interconnect_0:Lab3_timer_sw_agent_read -> Lab3:timer_sw_agent_read
	wire   [3:0] mm_interconnect_0_lab3_timer_sw_agent_byteenable;      // mm_interconnect_0:Lab3_timer_sw_agent_byteenable -> Lab3:timer_sw_agent_byteenable
	wire         mm_interconnect_0_lab3_timer_sw_agent_readdatavalid;   // Lab3:timer_sw_agent_readdatavalid -> mm_interconnect_0:Lab3_timer_sw_agent_readdatavalid
	wire         mm_interconnect_0_lab3_timer_sw_agent_write;           // mm_interconnect_0:Lab3_timer_sw_agent_write -> Lab3:timer_sw_agent_write
	wire  [31:0] mm_interconnect_0_lab3_timer_sw_agent_writedata;       // mm_interconnect_0:Lab3_timer_sw_agent_writedata -> Lab3:timer_sw_agent_writedata
	wire         irq_mapper_receiver0_irq;                              // DEBUG:av_irq -> irq_mapper:receiver0_irq
	wire  [15:0] lab3_platform_irq_rx_irq;                              // irq_mapper:sender_irq -> Lab3:platform_irq_rx_irq
	wire         rst_controller_reset_out_reset;                        // rst_controller:reset_out -> [DEBUG:rst_n, HEX1:reset_n, HEX2:reset_n, HEX3:reset_n, HEX4:reset_n, HEX5:reset_n, Lab3:reset_reset, SRAM:reset, irq_mapper:reset, mm_interconnect_0:Lab3_reset_reset_bridge_in_reset_reset, rst_translator:in_reset, switches:reset_n]
	wire         rst_controller_reset_out_reset_req;                    // rst_controller:reset_req -> [SRAM:reset_req, rst_translator:reset_req_in]
	wire         rst_controller_001_reset_out_reset;                    // rst_controller_001:reset_out -> [HEX0:reset_n, mm_interconnect_0:HEX0_reset_reset_bridge_in_reset_reset]

	Lab3_DEBUG debug (
		.clk            (clk_clk),                                               //               clk.clk
		.rst_n          (~rst_controller_reset_out_reset),                       //             reset.reset_n
		.av_chipselect  (mm_interconnect_0_debug_avalon_jtag_slave_chipselect),  // avalon_jtag_slave.chipselect
		.av_address     (mm_interconnect_0_debug_avalon_jtag_slave_address),     //                  .address
		.av_read_n      (~mm_interconnect_0_debug_avalon_jtag_slave_read),       //                  .read_n
		.av_readdata    (mm_interconnect_0_debug_avalon_jtag_slave_readdata),    //                  .readdata
		.av_write_n     (~mm_interconnect_0_debug_avalon_jtag_slave_write),      //                  .write_n
		.av_writedata   (mm_interconnect_0_debug_avalon_jtag_slave_writedata),   //                  .writedata
		.av_waitrequest (mm_interconnect_0_debug_avalon_jtag_slave_waitrequest), //                  .waitrequest
		.av_irq         (irq_mapper_receiver0_irq)                               //               irq.irq
	);

	Lab3_HEX0 hex0 (
		.clk        (clk_clk),                              //                 clk.clk
		.reset_n    (~rst_controller_001_reset_out_reset),  //               reset.reset_n
		.address    (mm_interconnect_0_hex0_s1_address),    //                  s1.address
		.write_n    (~mm_interconnect_0_hex0_s1_write),     //                    .write_n
		.writedata  (mm_interconnect_0_hex0_s1_writedata),  //                    .writedata
		.chipselect (mm_interconnect_0_hex0_s1_chipselect), //                    .chipselect
		.readdata   (mm_interconnect_0_hex0_s1_readdata),   //                    .readdata
		.out_port   (hex0_export)                           // external_connection.export
	);

	Lab3_HEX0 hex1 (
		.clk        (clk_clk),                              //                 clk.clk
		.reset_n    (~rst_controller_reset_out_reset),      //               reset.reset_n
		.address    (mm_interconnect_0_hex1_s1_address),    //                  s1.address
		.write_n    (~mm_interconnect_0_hex1_s1_write),     //                    .write_n
		.writedata  (mm_interconnect_0_hex1_s1_writedata),  //                    .writedata
		.chipselect (mm_interconnect_0_hex1_s1_chipselect), //                    .chipselect
		.readdata   (mm_interconnect_0_hex1_s1_readdata),   //                    .readdata
		.out_port   (hex1_export)                           // external_connection.export
	);

	Lab3_HEX0 hex2 (
		.clk        (clk_clk),                              //                 clk.clk
		.reset_n    (~rst_controller_reset_out_reset),      //               reset.reset_n
		.address    (mm_interconnect_0_hex2_s1_address),    //                  s1.address
		.write_n    (~mm_interconnect_0_hex2_s1_write),     //                    .write_n
		.writedata  (mm_interconnect_0_hex2_s1_writedata),  //                    .writedata
		.chipselect (mm_interconnect_0_hex2_s1_chipselect), //                    .chipselect
		.readdata   (mm_interconnect_0_hex2_s1_readdata),   //                    .readdata
		.out_port   (hex2_export)                           // external_connection.export
	);

	Lab3_HEX0 hex3 (
		.clk        (clk_clk),                              //                 clk.clk
		.reset_n    (~rst_controller_reset_out_reset),      //               reset.reset_n
		.address    (mm_interconnect_0_hex3_s1_address),    //                  s1.address
		.write_n    (~mm_interconnect_0_hex3_s1_write),     //                    .write_n
		.writedata  (mm_interconnect_0_hex3_s1_writedata),  //                    .writedata
		.chipselect (mm_interconnect_0_hex3_s1_chipselect), //                    .chipselect
		.readdata   (mm_interconnect_0_hex3_s1_readdata),   //                    .readdata
		.out_port   (hex3_export)                           // external_connection.export
	);

	Lab3_HEX0 hex4 (
		.clk        (clk_clk),                              //                 clk.clk
		.reset_n    (~rst_controller_reset_out_reset),      //               reset.reset_n
		.address    (mm_interconnect_0_hex4_s1_address),    //                  s1.address
		.write_n    (~mm_interconnect_0_hex4_s1_write),     //                    .write_n
		.writedata  (mm_interconnect_0_hex4_s1_writedata),  //                    .writedata
		.chipselect (mm_interconnect_0_hex4_s1_chipselect), //                    .chipselect
		.readdata   (mm_interconnect_0_hex4_s1_readdata),   //                    .readdata
		.out_port   (hex4_export)                           // external_connection.export
	);

	Lab3_HEX0 hex5 (
		.clk        (clk_clk),                              //                 clk.clk
		.reset_n    (~rst_controller_reset_out_reset),      //               reset.reset_n
		.address    (mm_interconnect_0_hex5_s1_address),    //                  s1.address
		.write_n    (~mm_interconnect_0_hex5_s1_write),     //                    .write_n
		.writedata  (mm_interconnect_0_hex5_s1_writedata),  //                    .writedata
		.chipselect (mm_interconnect_0_hex5_s1_chipselect), //                    .chipselect
		.readdata   (mm_interconnect_0_hex5_s1_readdata),   //                    .readdata
		.out_port   (hex5_export)                           // external_connection.export
	);

	Lab3_Lab3 lab3 (
		.clk                          (clk_clk),                                             //                 clk.clk
		.reset_reset                  (rst_controller_reset_out_reset),                      //               reset.reset
		.platform_irq_rx_irq          (lab3_platform_irq_rx_irq),                            //     platform_irq_rx.irq
		.ndm_reset_in_reset           (lab3_dbg_reset_out_reset),                            //        ndm_reset_in.reset
		.timer_sw_agent_write         (mm_interconnect_0_lab3_timer_sw_agent_write),         //      timer_sw_agent.write
		.timer_sw_agent_writedata     (mm_interconnect_0_lab3_timer_sw_agent_writedata),     //                    .writedata
		.timer_sw_agent_byteenable    (mm_interconnect_0_lab3_timer_sw_agent_byteenable),    //                    .byteenable
		.timer_sw_agent_address       (mm_interconnect_0_lab3_timer_sw_agent_address),       //                    .address
		.timer_sw_agent_read          (mm_interconnect_0_lab3_timer_sw_agent_read),          //                    .read
		.timer_sw_agent_readdata      (mm_interconnect_0_lab3_timer_sw_agent_readdata),      //                    .readdata
		.timer_sw_agent_readdatavalid (mm_interconnect_0_lab3_timer_sw_agent_readdatavalid), //                    .readdatavalid
		.timer_sw_agent_waitrequest   (mm_interconnect_0_lab3_timer_sw_agent_waitrequest),   //                    .waitrequest
		.instruction_manager_awaddr   (lab3_instruction_manager_awaddr),                     // instruction_manager.awaddr
		.instruction_manager_awprot   (lab3_instruction_manager_awprot),                     //                    .awprot
		.instruction_manager_awvalid  (lab3_instruction_manager_awvalid),                    //                    .awvalid
		.instruction_manager_awready  (lab3_instruction_manager_awready),                    //                    .awready
		.instruction_manager_wdata    (lab3_instruction_manager_wdata),                      //                    .wdata
		.instruction_manager_wstrb    (lab3_instruction_manager_wstrb),                      //                    .wstrb
		.instruction_manager_wvalid   (lab3_instruction_manager_wvalid),                     //                    .wvalid
		.instruction_manager_wready   (lab3_instruction_manager_wready),                     //                    .wready
		.instruction_manager_bresp    (lab3_instruction_manager_bresp),                      //                    .bresp
		.instruction_manager_bvalid   (lab3_instruction_manager_bvalid),                     //                    .bvalid
		.instruction_manager_bready   (lab3_instruction_manager_bready),                     //                    .bready
		.instruction_manager_araddr   (lab3_instruction_manager_araddr),                     //                    .araddr
		.instruction_manager_arprot   (lab3_instruction_manager_arprot),                     //                    .arprot
		.instruction_manager_arvalid  (lab3_instruction_manager_arvalid),                    //                    .arvalid
		.instruction_manager_arready  (lab3_instruction_manager_arready),                    //                    .arready
		.instruction_manager_rdata    (lab3_instruction_manager_rdata),                      //                    .rdata
		.instruction_manager_rresp    (lab3_instruction_manager_rresp),                      //                    .rresp
		.instruction_manager_rvalid   (lab3_instruction_manager_rvalid),                     //                    .rvalid
		.instruction_manager_rready   (lab3_instruction_manager_rready),                     //                    .rready
		.data_manager_awaddr          (lab3_data_manager_awaddr),                            //        data_manager.awaddr
		.data_manager_awprot          (lab3_data_manager_awprot),                            //                    .awprot
		.data_manager_awvalid         (lab3_data_manager_awvalid),                           //                    .awvalid
		.data_manager_awready         (lab3_data_manager_awready),                           //                    .awready
		.data_manager_wdata           (lab3_data_manager_wdata),                             //                    .wdata
		.data_manager_wstrb           (lab3_data_manager_wstrb),                             //                    .wstrb
		.data_manager_wvalid          (lab3_data_manager_wvalid),                            //                    .wvalid
		.data_manager_wready          (lab3_data_manager_wready),                            //                    .wready
		.data_manager_bresp           (lab3_data_manager_bresp),                             //                    .bresp
		.data_manager_bvalid          (lab3_data_manager_bvalid),                            //                    .bvalid
		.data_manager_bready          (lab3_data_manager_bready),                            //                    .bready
		.data_manager_araddr          (lab3_data_manager_araddr),                            //                    .araddr
		.data_manager_arprot          (lab3_data_manager_arprot),                            //                    .arprot
		.data_manager_arvalid         (lab3_data_manager_arvalid),                           //                    .arvalid
		.data_manager_arready         (lab3_data_manager_arready),                           //                    .arready
		.data_manager_rdata           (lab3_data_manager_rdata),                             //                    .rdata
		.data_manager_rresp           (lab3_data_manager_rresp),                             //                    .rresp
		.data_manager_rvalid          (lab3_data_manager_rvalid),                            //                    .rvalid
		.data_manager_rready          (lab3_data_manager_rready),                            //                    .rready
		.dm_agent_write               (mm_interconnect_0_lab3_dm_agent_write),               //            dm_agent.write
		.dm_agent_writedata           (mm_interconnect_0_lab3_dm_agent_writedata),           //                    .writedata
		.dm_agent_address             (mm_interconnect_0_lab3_dm_agent_address),             //                    .address
		.dm_agent_read                (mm_interconnect_0_lab3_dm_agent_read),                //                    .read
		.dm_agent_readdata            (mm_interconnect_0_lab3_dm_agent_readdata),            //                    .readdata
		.dm_agent_readdatavalid       (mm_interconnect_0_lab3_dm_agent_readdatavalid),       //                    .readdatavalid
		.dm_agent_waitrequest         (mm_interconnect_0_lab3_dm_agent_waitrequest),         //                    .waitrequest
		.dbg_reset_out_reset          (lab3_dbg_reset_out_reset)                             //       dbg_reset_out.reset
	);

	Lab3_SRAM sram (
		.clk        (clk_clk),                              //   clk1.clk
		.address    (mm_interconnect_0_sram_s1_address),    //     s1.address
		.clken      (mm_interconnect_0_sram_s1_clken),      //       .clken
		.chipselect (mm_interconnect_0_sram_s1_chipselect), //       .chipselect
		.write      (mm_interconnect_0_sram_s1_write),      //       .write
		.readdata   (mm_interconnect_0_sram_s1_readdata),   //       .readdata
		.writedata  (mm_interconnect_0_sram_s1_writedata),  //       .writedata
		.byteenable (mm_interconnect_0_sram_s1_byteenable), //       .byteenable
		.reset      (rst_controller_reset_out_reset),       // reset1.reset
		.reset_req  (rst_controller_reset_out_reset_req),   //       .reset_req
		.freeze     (1'b0)                                  // (terminated)
	);

	Lab3_switches switches (
		.clk      (clk_clk),                                //                 clk.clk
		.reset_n  (~rst_controller_reset_out_reset),        //               reset.reset_n
		.address  (mm_interconnect_0_switches_s1_address),  //                  s1.address
		.readdata (mm_interconnect_0_switches_s1_readdata), //                    .readdata
		.in_port  (sw_export)                               // external_connection.export
	);

	Lab3_mm_interconnect_0 mm_interconnect_0 (
		.Lab3_data_manager_awaddr               (lab3_data_manager_awaddr),                              //                Lab3_data_manager.awaddr
		.Lab3_data_manager_awprot               (lab3_data_manager_awprot),                              //                                 .awprot
		.Lab3_data_manager_awvalid              (lab3_data_manager_awvalid),                             //                                 .awvalid
		.Lab3_data_manager_awready              (lab3_data_manager_awready),                             //                                 .awready
		.Lab3_data_manager_wdata                (lab3_data_manager_wdata),                               //                                 .wdata
		.Lab3_data_manager_wstrb                (lab3_data_manager_wstrb),                               //                                 .wstrb
		.Lab3_data_manager_wvalid               (lab3_data_manager_wvalid),                              //                                 .wvalid
		.Lab3_data_manager_wready               (lab3_data_manager_wready),                              //                                 .wready
		.Lab3_data_manager_bresp                (lab3_data_manager_bresp),                               //                                 .bresp
		.Lab3_data_manager_bvalid               (lab3_data_manager_bvalid),                              //                                 .bvalid
		.Lab3_data_manager_bready               (lab3_data_manager_bready),                              //                                 .bready
		.Lab3_data_manager_araddr               (lab3_data_manager_araddr),                              //                                 .araddr
		.Lab3_data_manager_arprot               (lab3_data_manager_arprot),                              //                                 .arprot
		.Lab3_data_manager_arvalid              (lab3_data_manager_arvalid),                             //                                 .arvalid
		.Lab3_data_manager_arready              (lab3_data_manager_arready),                             //                                 .arready
		.Lab3_data_manager_rdata                (lab3_data_manager_rdata),                               //                                 .rdata
		.Lab3_data_manager_rresp                (lab3_data_manager_rresp),                               //                                 .rresp
		.Lab3_data_manager_rvalid               (lab3_data_manager_rvalid),                              //                                 .rvalid
		.Lab3_data_manager_rready               (lab3_data_manager_rready),                              //                                 .rready
		.Lab3_instruction_manager_awaddr        (lab3_instruction_manager_awaddr),                       //         Lab3_instruction_manager.awaddr
		.Lab3_instruction_manager_awprot        (lab3_instruction_manager_awprot),                       //                                 .awprot
		.Lab3_instruction_manager_awvalid       (lab3_instruction_manager_awvalid),                      //                                 .awvalid
		.Lab3_instruction_manager_awready       (lab3_instruction_manager_awready),                      //                                 .awready
		.Lab3_instruction_manager_wdata         (lab3_instruction_manager_wdata),                        //                                 .wdata
		.Lab3_instruction_manager_wstrb         (lab3_instruction_manager_wstrb),                        //                                 .wstrb
		.Lab3_instruction_manager_wvalid        (lab3_instruction_manager_wvalid),                       //                                 .wvalid
		.Lab3_instruction_manager_wready        (lab3_instruction_manager_wready),                       //                                 .wready
		.Lab3_instruction_manager_bresp         (lab3_instruction_manager_bresp),                        //                                 .bresp
		.Lab3_instruction_manager_bvalid        (lab3_instruction_manager_bvalid),                       //                                 .bvalid
		.Lab3_instruction_manager_bready        (lab3_instruction_manager_bready),                       //                                 .bready
		.Lab3_instruction_manager_araddr        (lab3_instruction_manager_araddr),                       //                                 .araddr
		.Lab3_instruction_manager_arprot        (lab3_instruction_manager_arprot),                       //                                 .arprot
		.Lab3_instruction_manager_arvalid       (lab3_instruction_manager_arvalid),                      //                                 .arvalid
		.Lab3_instruction_manager_arready       (lab3_instruction_manager_arready),                      //                                 .arready
		.Lab3_instruction_manager_rdata         (lab3_instruction_manager_rdata),                        //                                 .rdata
		.Lab3_instruction_manager_rresp         (lab3_instruction_manager_rresp),                        //                                 .rresp
		.Lab3_instruction_manager_rvalid        (lab3_instruction_manager_rvalid),                       //                                 .rvalid
		.Lab3_instruction_manager_rready        (lab3_instruction_manager_rready),                       //                                 .rready
		.clk_0_clk_clk                          (clk_clk),                                               //                        clk_0_clk.clk
		.HEX0_reset_reset_bridge_in_reset_reset (rst_controller_001_reset_out_reset),                    // HEX0_reset_reset_bridge_in_reset.reset
		.Lab3_reset_reset_bridge_in_reset_reset (rst_controller_reset_out_reset),                        // Lab3_reset_reset_bridge_in_reset.reset
		.DEBUG_avalon_jtag_slave_address        (mm_interconnect_0_debug_avalon_jtag_slave_address),     //          DEBUG_avalon_jtag_slave.address
		.DEBUG_avalon_jtag_slave_write          (mm_interconnect_0_debug_avalon_jtag_slave_write),       //                                 .write
		.DEBUG_avalon_jtag_slave_read           (mm_interconnect_0_debug_avalon_jtag_slave_read),        //                                 .read
		.DEBUG_avalon_jtag_slave_readdata       (mm_interconnect_0_debug_avalon_jtag_slave_readdata),    //                                 .readdata
		.DEBUG_avalon_jtag_slave_writedata      (mm_interconnect_0_debug_avalon_jtag_slave_writedata),   //                                 .writedata
		.DEBUG_avalon_jtag_slave_waitrequest    (mm_interconnect_0_debug_avalon_jtag_slave_waitrequest), //                                 .waitrequest
		.DEBUG_avalon_jtag_slave_chipselect     (mm_interconnect_0_debug_avalon_jtag_slave_chipselect),  //                                 .chipselect
		.HEX0_s1_address                        (mm_interconnect_0_hex0_s1_address),                     //                          HEX0_s1.address
		.HEX0_s1_write                          (mm_interconnect_0_hex0_s1_write),                       //                                 .write
		.HEX0_s1_readdata                       (mm_interconnect_0_hex0_s1_readdata),                    //                                 .readdata
		.HEX0_s1_writedata                      (mm_interconnect_0_hex0_s1_writedata),                   //                                 .writedata
		.HEX0_s1_chipselect                     (mm_interconnect_0_hex0_s1_chipselect),                  //                                 .chipselect
		.HEX1_s1_address                        (mm_interconnect_0_hex1_s1_address),                     //                          HEX1_s1.address
		.HEX1_s1_write                          (mm_interconnect_0_hex1_s1_write),                       //                                 .write
		.HEX1_s1_readdata                       (mm_interconnect_0_hex1_s1_readdata),                    //                                 .readdata
		.HEX1_s1_writedata                      (mm_interconnect_0_hex1_s1_writedata),                   //                                 .writedata
		.HEX1_s1_chipselect                     (mm_interconnect_0_hex1_s1_chipselect),                  //                                 .chipselect
		.HEX2_s1_address                        (mm_interconnect_0_hex2_s1_address),                     //                          HEX2_s1.address
		.HEX2_s1_write                          (mm_interconnect_0_hex2_s1_write),                       //                                 .write
		.HEX2_s1_readdata                       (mm_interconnect_0_hex2_s1_readdata),                    //                                 .readdata
		.HEX2_s1_writedata                      (mm_interconnect_0_hex2_s1_writedata),                   //                                 .writedata
		.HEX2_s1_chipselect                     (mm_interconnect_0_hex2_s1_chipselect),                  //                                 .chipselect
		.HEX3_s1_address                        (mm_interconnect_0_hex3_s1_address),                     //                          HEX3_s1.address
		.HEX3_s1_write                          (mm_interconnect_0_hex3_s1_write),                       //                                 .write
		.HEX3_s1_readdata                       (mm_interconnect_0_hex3_s1_readdata),                    //                                 .readdata
		.HEX3_s1_writedata                      (mm_interconnect_0_hex3_s1_writedata),                   //                                 .writedata
		.HEX3_s1_chipselect                     (mm_interconnect_0_hex3_s1_chipselect),                  //                                 .chipselect
		.HEX4_s1_address                        (mm_interconnect_0_hex4_s1_address),                     //                          HEX4_s1.address
		.HEX4_s1_write                          (mm_interconnect_0_hex4_s1_write),                       //                                 .write
		.HEX4_s1_readdata                       (mm_interconnect_0_hex4_s1_readdata),                    //                                 .readdata
		.HEX4_s1_writedata                      (mm_interconnect_0_hex4_s1_writedata),                   //                                 .writedata
		.HEX4_s1_chipselect                     (mm_interconnect_0_hex4_s1_chipselect),                  //                                 .chipselect
		.HEX5_s1_address                        (mm_interconnect_0_hex5_s1_address),                     //                          HEX5_s1.address
		.HEX5_s1_write                          (mm_interconnect_0_hex5_s1_write),                       //                                 .write
		.HEX5_s1_readdata                       (mm_interconnect_0_hex5_s1_readdata),                    //                                 .readdata
		.HEX5_s1_writedata                      (mm_interconnect_0_hex5_s1_writedata),                   //                                 .writedata
		.HEX5_s1_chipselect                     (mm_interconnect_0_hex5_s1_chipselect),                  //                                 .chipselect
		.Lab3_dm_agent_address                  (mm_interconnect_0_lab3_dm_agent_address),               //                    Lab3_dm_agent.address
		.Lab3_dm_agent_write                    (mm_interconnect_0_lab3_dm_agent_write),                 //                                 .write
		.Lab3_dm_agent_read                     (mm_interconnect_0_lab3_dm_agent_read),                  //                                 .read
		.Lab3_dm_agent_readdata                 (mm_interconnect_0_lab3_dm_agent_readdata),              //                                 .readdata
		.Lab3_dm_agent_writedata                (mm_interconnect_0_lab3_dm_agent_writedata),             //                                 .writedata
		.Lab3_dm_agent_readdatavalid            (mm_interconnect_0_lab3_dm_agent_readdatavalid),         //                                 .readdatavalid
		.Lab3_dm_agent_waitrequest              (mm_interconnect_0_lab3_dm_agent_waitrequest),           //                                 .waitrequest
		.Lab3_timer_sw_agent_address            (mm_interconnect_0_lab3_timer_sw_agent_address),         //              Lab3_timer_sw_agent.address
		.Lab3_timer_sw_agent_write              (mm_interconnect_0_lab3_timer_sw_agent_write),           //                                 .write
		.Lab3_timer_sw_agent_read               (mm_interconnect_0_lab3_timer_sw_agent_read),            //                                 .read
		.Lab3_timer_sw_agent_readdata           (mm_interconnect_0_lab3_timer_sw_agent_readdata),        //                                 .readdata
		.Lab3_timer_sw_agent_writedata          (mm_interconnect_0_lab3_timer_sw_agent_writedata),       //                                 .writedata
		.Lab3_timer_sw_agent_byteenable         (mm_interconnect_0_lab3_timer_sw_agent_byteenable),      //                                 .byteenable
		.Lab3_timer_sw_agent_readdatavalid      (mm_interconnect_0_lab3_timer_sw_agent_readdatavalid),   //                                 .readdatavalid
		.Lab3_timer_sw_agent_waitrequest        (mm_interconnect_0_lab3_timer_sw_agent_waitrequest),     //                                 .waitrequest
		.SRAM_s1_address                        (mm_interconnect_0_sram_s1_address),                     //                          SRAM_s1.address
		.SRAM_s1_write                          (mm_interconnect_0_sram_s1_write),                       //                                 .write
		.SRAM_s1_readdata                       (mm_interconnect_0_sram_s1_readdata),                    //                                 .readdata
		.SRAM_s1_writedata                      (mm_interconnect_0_sram_s1_writedata),                   //                                 .writedata
		.SRAM_s1_byteenable                     (mm_interconnect_0_sram_s1_byteenable),                  //                                 .byteenable
		.SRAM_s1_chipselect                     (mm_interconnect_0_sram_s1_chipselect),                  //                                 .chipselect
		.SRAM_s1_clken                          (mm_interconnect_0_sram_s1_clken),                       //                                 .clken
		.switches_s1_address                    (mm_interconnect_0_switches_s1_address),                 //                      switches_s1.address
		.switches_s1_readdata                   (mm_interconnect_0_switches_s1_readdata)                 //                                 .readdata
	);

	Lab3_irq_mapper irq_mapper (
		.clk           (clk_clk),                        //       clk.clk
		.reset         (rst_controller_reset_out_reset), // clk_reset.reset
		.receiver0_irq (irq_mapper_receiver0_irq),       // receiver0.irq
		.sender_irq    (lab3_platform_irq_rx_irq)        //    sender.irq
	);

	altera_reset_controller #(
		.NUM_RESET_INPUTS          (1),
		.OUTPUT_RESET_SYNC_EDGES   ("deassert"),
		.SYNC_DEPTH                (2),
		.RESET_REQUEST_PRESENT     (1),
		.RESET_REQ_WAIT_TIME       (1),
		.MIN_RST_ASSERTION_TIME    (3),
		.RESET_REQ_EARLY_DSRT_TIME (1),
		.USE_RESET_REQUEST_IN0     (0),
		.USE_RESET_REQUEST_IN1     (0),
		.USE_RESET_REQUEST_IN2     (0),
		.USE_RESET_REQUEST_IN3     (0),
		.USE_RESET_REQUEST_IN4     (0),
		.USE_RESET_REQUEST_IN5     (0),
		.USE_RESET_REQUEST_IN6     (0),
		.USE_RESET_REQUEST_IN7     (0),
		.USE_RESET_REQUEST_IN8     (0),
		.USE_RESET_REQUEST_IN9     (0),
		.USE_RESET_REQUEST_IN10    (0),
		.USE_RESET_REQUEST_IN11    (0),
		.USE_RESET_REQUEST_IN12    (0),
		.USE_RESET_REQUEST_IN13    (0),
		.USE_RESET_REQUEST_IN14    (0),
		.USE_RESET_REQUEST_IN15    (0),
		.ADAPT_RESET_REQUEST       (0)
	) rst_controller (
		.reset_in0      (lab3_dbg_reset_out_reset),           // reset_in0.reset
		.clk            (clk_clk),                            //       clk.clk
		.reset_out      (rst_controller_reset_out_reset),     // reset_out.reset
		.reset_req      (rst_controller_reset_out_reset_req), //          .reset_req
		.reset_req_in0  (1'b0),                               // (terminated)
		.reset_in1      (1'b0),                               // (terminated)
		.reset_req_in1  (1'b0),                               // (terminated)
		.reset_in2      (1'b0),                               // (terminated)
		.reset_req_in2  (1'b0),                               // (terminated)
		.reset_in3      (1'b0),                               // (terminated)
		.reset_req_in3  (1'b0),                               // (terminated)
		.reset_in4      (1'b0),                               // (terminated)
		.reset_req_in4  (1'b0),                               // (terminated)
		.reset_in5      (1'b0),                               // (terminated)
		.reset_req_in5  (1'b0),                               // (terminated)
		.reset_in6      (1'b0),                               // (terminated)
		.reset_req_in6  (1'b0),                               // (terminated)
		.reset_in7      (1'b0),                               // (terminated)
		.reset_req_in7  (1'b0),                               // (terminated)
		.reset_in8      (1'b0),                               // (terminated)
		.reset_req_in8  (1'b0),                               // (terminated)
		.reset_in9      (1'b0),                               // (terminated)
		.reset_req_in9  (1'b0),                               // (terminated)
		.reset_in10     (1'b0),                               // (terminated)
		.reset_req_in10 (1'b0),                               // (terminated)
		.reset_in11     (1'b0),                               // (terminated)
		.reset_req_in11 (1'b0),                               // (terminated)
		.reset_in12     (1'b0),                               // (terminated)
		.reset_req_in12 (1'b0),                               // (terminated)
		.reset_in13     (1'b0),                               // (terminated)
		.reset_req_in13 (1'b0),                               // (terminated)
		.reset_in14     (1'b0),                               // (terminated)
		.reset_req_in14 (1'b0),                               // (terminated)
		.reset_in15     (1'b0),                               // (terminated)
		.reset_req_in15 (1'b0)                                // (terminated)
	);

	altera_reset_controller #(
		.NUM_RESET_INPUTS          (2),
		.OUTPUT_RESET_SYNC_EDGES   ("deassert"),
		.SYNC_DEPTH                (2),
		.RESET_REQUEST_PRESENT     (0),
		.RESET_REQ_WAIT_TIME       (1),
		.MIN_RST_ASSERTION_TIME    (3),
		.RESET_REQ_EARLY_DSRT_TIME (1),
		.USE_RESET_REQUEST_IN0     (0),
		.USE_RESET_REQUEST_IN1     (0),
		.USE_RESET_REQUEST_IN2     (0),
		.USE_RESET_REQUEST_IN3     (0),
		.USE_RESET_REQUEST_IN4     (0),
		.USE_RESET_REQUEST_IN5     (0),
		.USE_RESET_REQUEST_IN6     (0),
		.USE_RESET_REQUEST_IN7     (0),
		.USE_RESET_REQUEST_IN8     (0),
		.USE_RESET_REQUEST_IN9     (0),
		.USE_RESET_REQUEST_IN10    (0),
		.USE_RESET_REQUEST_IN11    (0),
		.USE_RESET_REQUEST_IN12    (0),
		.USE_RESET_REQUEST_IN13    (0),
		.USE_RESET_REQUEST_IN14    (0),
		.USE_RESET_REQUEST_IN15    (0),
		.ADAPT_RESET_REQUEST       (0)
	) rst_controller_001 (
		.reset_in0      (lab3_dbg_reset_out_reset),           // reset_in0.reset
		.reset_in1      (lab3_dbg_reset_out_reset),           // reset_in1.reset
		.clk            (clk_clk),                            //       clk.clk
		.reset_out      (rst_controller_001_reset_out_reset), // reset_out.reset
		.reset_req      (),                                   // (terminated)
		.reset_req_in0  (1'b0),                               // (terminated)
		.reset_req_in1  (1'b0),                               // (terminated)
		.reset_in2      (1'b0),                               // (terminated)
		.reset_req_in2  (1'b0),                               // (terminated)
		.reset_in3      (1'b0),                               // (terminated)
		.reset_req_in3  (1'b0),                               // (terminated)
		.reset_in4      (1'b0),                               // (terminated)
		.reset_req_in4  (1'b0),                               // (terminated)
		.reset_in5      (1'b0),                               // (terminated)
		.reset_req_in5  (1'b0),                               // (terminated)
		.reset_in6      (1'b0),                               // (terminated)
		.reset_req_in6  (1'b0),                               // (terminated)
		.reset_in7      (1'b0),                               // (terminated)
		.reset_req_in7  (1'b0),                               // (terminated)
		.reset_in8      (1'b0),                               // (terminated)
		.reset_req_in8  (1'b0),                               // (terminated)
		.reset_in9      (1'b0),                               // (terminated)
		.reset_req_in9  (1'b0),                               // (terminated)
		.reset_in10     (1'b0),                               // (terminated)
		.reset_req_in10 (1'b0),                               // (terminated)
		.reset_in11     (1'b0),                               // (terminated)
		.reset_req_in11 (1'b0),                               // (terminated)
		.reset_in12     (1'b0),                               // (terminated)
		.reset_req_in12 (1'b0),                               // (terminated)
		.reset_in13     (1'b0),                               // (terminated)
		.reset_req_in13 (1'b0),                               // (terminated)
		.reset_in14     (1'b0),                               // (terminated)
		.reset_req_in14 (1'b0),                               // (terminated)
		.reset_in15     (1'b0),                               // (terminated)
		.reset_req_in15 (1'b0)                                // (terminated)
	);

endmodule
