// Lab4.v

// Generated using ACDS version 23.1 991

`timescale 1 ps / 1 ps
module Lab4 (
		input  wire [3:0]  buttons_export,   //    buttons.export
		input  wire        clk_clk,          //        clk.clk
		output wire [9:0]  leds_export,      //       leds.export
		output wire        sdram_clk_clk,    //  sdram_clk.clk
		output wire [12:0] sdram_wire_addr,  // sdram_wire.addr
		output wire [1:0]  sdram_wire_ba,    //           .ba
		output wire        sdram_wire_cas_n, //           .cas_n
		output wire        sdram_wire_cke,   //           .cke
		output wire        sdram_wire_cs_n,  //           .cs_n
		inout  wire [15:0] sdram_wire_dq,    //           .dq
		output wire [1:0]  sdram_wire_dqm,   //           .dqm
		output wire        sdram_wire_ras_n, //           .ras_n
		output wire        sdram_wire_we_n   //           .we_n
	);

	wire         clocks_sys_clk_clk;                                            // CLOCKS:sys_clk_clk -> [BUTTONS:clk, DEBUG:clk, LEDs:clk, NIOSV_FreeRTOS:clk, SDRAM:clk, irq_mapper:clk, mm_interconnect_0:CLOCKS_sys_clk_clk, rst_controller:clk]
	wire         niosv_freertos_dbg_reset_out_reset;                            // NIOSV_FreeRTOS:dbg_reset_out_reset -> [CLOCKS:ref_reset_reset, NIOSV_FreeRTOS:ndm_reset_in_reset, rst_controller:reset_in0]
	wire  [31:0] niosv_freertos_data_manager_awaddr;                            // NIOSV_FreeRTOS:data_manager_awaddr -> mm_interconnect_0:NIOSV_FreeRTOS_data_manager_awaddr
	wire   [1:0] niosv_freertos_data_manager_bresp;                             // mm_interconnect_0:NIOSV_FreeRTOS_data_manager_bresp -> NIOSV_FreeRTOS:data_manager_bresp
	wire         niosv_freertos_data_manager_arready;                           // mm_interconnect_0:NIOSV_FreeRTOS_data_manager_arready -> NIOSV_FreeRTOS:data_manager_arready
	wire  [31:0] niosv_freertos_data_manager_rdata;                             // mm_interconnect_0:NIOSV_FreeRTOS_data_manager_rdata -> NIOSV_FreeRTOS:data_manager_rdata
	wire   [3:0] niosv_freertos_data_manager_wstrb;                             // NIOSV_FreeRTOS:data_manager_wstrb -> mm_interconnect_0:NIOSV_FreeRTOS_data_manager_wstrb
	wire         niosv_freertos_data_manager_wready;                            // mm_interconnect_0:NIOSV_FreeRTOS_data_manager_wready -> NIOSV_FreeRTOS:data_manager_wready
	wire         niosv_freertos_data_manager_awready;                           // mm_interconnect_0:NIOSV_FreeRTOS_data_manager_awready -> NIOSV_FreeRTOS:data_manager_awready
	wire         niosv_freertos_data_manager_rready;                            // NIOSV_FreeRTOS:data_manager_rready -> mm_interconnect_0:NIOSV_FreeRTOS_data_manager_rready
	wire         niosv_freertos_data_manager_bready;                            // NIOSV_FreeRTOS:data_manager_bready -> mm_interconnect_0:NIOSV_FreeRTOS_data_manager_bready
	wire         niosv_freertos_data_manager_wvalid;                            // NIOSV_FreeRTOS:data_manager_wvalid -> mm_interconnect_0:NIOSV_FreeRTOS_data_manager_wvalid
	wire  [31:0] niosv_freertos_data_manager_araddr;                            // NIOSV_FreeRTOS:data_manager_araddr -> mm_interconnect_0:NIOSV_FreeRTOS_data_manager_araddr
	wire   [2:0] niosv_freertos_data_manager_arprot;                            // NIOSV_FreeRTOS:data_manager_arprot -> mm_interconnect_0:NIOSV_FreeRTOS_data_manager_arprot
	wire   [1:0] niosv_freertos_data_manager_rresp;                             // mm_interconnect_0:NIOSV_FreeRTOS_data_manager_rresp -> NIOSV_FreeRTOS:data_manager_rresp
	wire   [2:0] niosv_freertos_data_manager_awprot;                            // NIOSV_FreeRTOS:data_manager_awprot -> mm_interconnect_0:NIOSV_FreeRTOS_data_manager_awprot
	wire  [31:0] niosv_freertos_data_manager_wdata;                             // NIOSV_FreeRTOS:data_manager_wdata -> mm_interconnect_0:NIOSV_FreeRTOS_data_manager_wdata
	wire         niosv_freertos_data_manager_arvalid;                           // NIOSV_FreeRTOS:data_manager_arvalid -> mm_interconnect_0:NIOSV_FreeRTOS_data_manager_arvalid
	wire         niosv_freertos_data_manager_bvalid;                            // mm_interconnect_0:NIOSV_FreeRTOS_data_manager_bvalid -> NIOSV_FreeRTOS:data_manager_bvalid
	wire         niosv_freertos_data_manager_awvalid;                           // NIOSV_FreeRTOS:data_manager_awvalid -> mm_interconnect_0:NIOSV_FreeRTOS_data_manager_awvalid
	wire         niosv_freertos_data_manager_rvalid;                            // mm_interconnect_0:NIOSV_FreeRTOS_data_manager_rvalid -> NIOSV_FreeRTOS:data_manager_rvalid
	wire  [31:0] niosv_freertos_instruction_manager_awaddr;                     // NIOSV_FreeRTOS:instruction_manager_awaddr -> mm_interconnect_0:NIOSV_FreeRTOS_instruction_manager_awaddr
	wire   [1:0] niosv_freertos_instruction_manager_bresp;                      // mm_interconnect_0:NIOSV_FreeRTOS_instruction_manager_bresp -> NIOSV_FreeRTOS:instruction_manager_bresp
	wire         niosv_freertos_instruction_manager_arready;                    // mm_interconnect_0:NIOSV_FreeRTOS_instruction_manager_arready -> NIOSV_FreeRTOS:instruction_manager_arready
	wire  [31:0] niosv_freertos_instruction_manager_rdata;                      // mm_interconnect_0:NIOSV_FreeRTOS_instruction_manager_rdata -> NIOSV_FreeRTOS:instruction_manager_rdata
	wire   [3:0] niosv_freertos_instruction_manager_wstrb;                      // NIOSV_FreeRTOS:instruction_manager_wstrb -> mm_interconnect_0:NIOSV_FreeRTOS_instruction_manager_wstrb
	wire         niosv_freertos_instruction_manager_wready;                     // mm_interconnect_0:NIOSV_FreeRTOS_instruction_manager_wready -> NIOSV_FreeRTOS:instruction_manager_wready
	wire         niosv_freertos_instruction_manager_awready;                    // mm_interconnect_0:NIOSV_FreeRTOS_instruction_manager_awready -> NIOSV_FreeRTOS:instruction_manager_awready
	wire         niosv_freertos_instruction_manager_rready;                     // NIOSV_FreeRTOS:instruction_manager_rready -> mm_interconnect_0:NIOSV_FreeRTOS_instruction_manager_rready
	wire         niosv_freertos_instruction_manager_bready;                     // NIOSV_FreeRTOS:instruction_manager_bready -> mm_interconnect_0:NIOSV_FreeRTOS_instruction_manager_bready
	wire         niosv_freertos_instruction_manager_wvalid;                     // NIOSV_FreeRTOS:instruction_manager_wvalid -> mm_interconnect_0:NIOSV_FreeRTOS_instruction_manager_wvalid
	wire  [31:0] niosv_freertos_instruction_manager_araddr;                     // NIOSV_FreeRTOS:instruction_manager_araddr -> mm_interconnect_0:NIOSV_FreeRTOS_instruction_manager_araddr
	wire   [2:0] niosv_freertos_instruction_manager_arprot;                     // NIOSV_FreeRTOS:instruction_manager_arprot -> mm_interconnect_0:NIOSV_FreeRTOS_instruction_manager_arprot
	wire   [1:0] niosv_freertos_instruction_manager_rresp;                      // mm_interconnect_0:NIOSV_FreeRTOS_instruction_manager_rresp -> NIOSV_FreeRTOS:instruction_manager_rresp
	wire   [2:0] niosv_freertos_instruction_manager_awprot;                     // NIOSV_FreeRTOS:instruction_manager_awprot -> mm_interconnect_0:NIOSV_FreeRTOS_instruction_manager_awprot
	wire  [31:0] niosv_freertos_instruction_manager_wdata;                      // NIOSV_FreeRTOS:instruction_manager_wdata -> mm_interconnect_0:NIOSV_FreeRTOS_instruction_manager_wdata
	wire         niosv_freertos_instruction_manager_arvalid;                    // NIOSV_FreeRTOS:instruction_manager_arvalid -> mm_interconnect_0:NIOSV_FreeRTOS_instruction_manager_arvalid
	wire         niosv_freertos_instruction_manager_bvalid;                     // mm_interconnect_0:NIOSV_FreeRTOS_instruction_manager_bvalid -> NIOSV_FreeRTOS:instruction_manager_bvalid
	wire         niosv_freertos_instruction_manager_awvalid;                    // NIOSV_FreeRTOS:instruction_manager_awvalid -> mm_interconnect_0:NIOSV_FreeRTOS_instruction_manager_awvalid
	wire         niosv_freertos_instruction_manager_rvalid;                     // mm_interconnect_0:NIOSV_FreeRTOS_instruction_manager_rvalid -> NIOSV_FreeRTOS:instruction_manager_rvalid
	wire         mm_interconnect_0_debug_avalon_jtag_slave_chipselect;          // mm_interconnect_0:DEBUG_avalon_jtag_slave_chipselect -> DEBUG:av_chipselect
	wire  [31:0] mm_interconnect_0_debug_avalon_jtag_slave_readdata;            // DEBUG:av_readdata -> mm_interconnect_0:DEBUG_avalon_jtag_slave_readdata
	wire         mm_interconnect_0_debug_avalon_jtag_slave_waitrequest;         // DEBUG:av_waitrequest -> mm_interconnect_0:DEBUG_avalon_jtag_slave_waitrequest
	wire   [0:0] mm_interconnect_0_debug_avalon_jtag_slave_address;             // mm_interconnect_0:DEBUG_avalon_jtag_slave_address -> DEBUG:av_address
	wire         mm_interconnect_0_debug_avalon_jtag_slave_read;                // mm_interconnect_0:DEBUG_avalon_jtag_slave_read -> DEBUG:av_read_n
	wire         mm_interconnect_0_debug_avalon_jtag_slave_write;               // mm_interconnect_0:DEBUG_avalon_jtag_slave_write -> DEBUG:av_write_n
	wire  [31:0] mm_interconnect_0_debug_avalon_jtag_slave_writedata;           // mm_interconnect_0:DEBUG_avalon_jtag_slave_writedata -> DEBUG:av_writedata
	wire  [31:0] mm_interconnect_0_niosv_freertos_dm_agent_readdata;            // NIOSV_FreeRTOS:dm_agent_readdata -> mm_interconnect_0:NIOSV_FreeRTOS_dm_agent_readdata
	wire         mm_interconnect_0_niosv_freertos_dm_agent_waitrequest;         // NIOSV_FreeRTOS:dm_agent_waitrequest -> mm_interconnect_0:NIOSV_FreeRTOS_dm_agent_waitrequest
	wire  [15:0] mm_interconnect_0_niosv_freertos_dm_agent_address;             // mm_interconnect_0:NIOSV_FreeRTOS_dm_agent_address -> NIOSV_FreeRTOS:dm_agent_address
	wire         mm_interconnect_0_niosv_freertos_dm_agent_read;                // mm_interconnect_0:NIOSV_FreeRTOS_dm_agent_read -> NIOSV_FreeRTOS:dm_agent_read
	wire         mm_interconnect_0_niosv_freertos_dm_agent_readdatavalid;       // NIOSV_FreeRTOS:dm_agent_readdatavalid -> mm_interconnect_0:NIOSV_FreeRTOS_dm_agent_readdatavalid
	wire         mm_interconnect_0_niosv_freertos_dm_agent_write;               // mm_interconnect_0:NIOSV_FreeRTOS_dm_agent_write -> NIOSV_FreeRTOS:dm_agent_write
	wire  [31:0] mm_interconnect_0_niosv_freertos_dm_agent_writedata;           // mm_interconnect_0:NIOSV_FreeRTOS_dm_agent_writedata -> NIOSV_FreeRTOS:dm_agent_writedata
	wire         mm_interconnect_0_sdram_s1_chipselect;                         // mm_interconnect_0:SDRAM_s1_chipselect -> SDRAM:az_cs
	wire  [15:0] mm_interconnect_0_sdram_s1_readdata;                           // SDRAM:za_data -> mm_interconnect_0:SDRAM_s1_readdata
	wire         mm_interconnect_0_sdram_s1_waitrequest;                        // SDRAM:za_waitrequest -> mm_interconnect_0:SDRAM_s1_waitrequest
	wire  [24:0] mm_interconnect_0_sdram_s1_address;                            // mm_interconnect_0:SDRAM_s1_address -> SDRAM:az_addr
	wire         mm_interconnect_0_sdram_s1_read;                               // mm_interconnect_0:SDRAM_s1_read -> SDRAM:az_rd_n
	wire   [1:0] mm_interconnect_0_sdram_s1_byteenable;                         // mm_interconnect_0:SDRAM_s1_byteenable -> SDRAM:az_be_n
	wire         mm_interconnect_0_sdram_s1_readdatavalid;                      // SDRAM:za_valid -> mm_interconnect_0:SDRAM_s1_readdatavalid
	wire         mm_interconnect_0_sdram_s1_write;                              // mm_interconnect_0:SDRAM_s1_write -> SDRAM:az_wr_n
	wire  [15:0] mm_interconnect_0_sdram_s1_writedata;                          // mm_interconnect_0:SDRAM_s1_writedata -> SDRAM:az_data
	wire  [31:0] mm_interconnect_0_buttons_s1_readdata;                         // BUTTONS:readdata -> mm_interconnect_0:BUTTONS_s1_readdata
	wire   [1:0] mm_interconnect_0_buttons_s1_address;                          // mm_interconnect_0:BUTTONS_s1_address -> BUTTONS:address
	wire         mm_interconnect_0_leds_s1_chipselect;                          // mm_interconnect_0:LEDs_s1_chipselect -> LEDs:chipselect
	wire  [31:0] mm_interconnect_0_leds_s1_readdata;                            // LEDs:readdata -> mm_interconnect_0:LEDs_s1_readdata
	wire   [2:0] mm_interconnect_0_leds_s1_address;                             // mm_interconnect_0:LEDs_s1_address -> LEDs:address
	wire         mm_interconnect_0_leds_s1_write;                               // mm_interconnect_0:LEDs_s1_write -> LEDs:write_n
	wire  [31:0] mm_interconnect_0_leds_s1_writedata;                           // mm_interconnect_0:LEDs_s1_writedata -> LEDs:writedata
	wire  [31:0] mm_interconnect_0_niosv_freertos_timer_sw_agent_readdata;      // NIOSV_FreeRTOS:timer_sw_agent_readdata -> mm_interconnect_0:NIOSV_FreeRTOS_timer_sw_agent_readdata
	wire         mm_interconnect_0_niosv_freertos_timer_sw_agent_waitrequest;   // NIOSV_FreeRTOS:timer_sw_agent_waitrequest -> mm_interconnect_0:NIOSV_FreeRTOS_timer_sw_agent_waitrequest
	wire   [5:0] mm_interconnect_0_niosv_freertos_timer_sw_agent_address;       // mm_interconnect_0:NIOSV_FreeRTOS_timer_sw_agent_address -> NIOSV_FreeRTOS:timer_sw_agent_address
	wire         mm_interconnect_0_niosv_freertos_timer_sw_agent_read;          // mm_interconnect_0:NIOSV_FreeRTOS_timer_sw_agent_read -> NIOSV_FreeRTOS:timer_sw_agent_read
	wire   [3:0] mm_interconnect_0_niosv_freertos_timer_sw_agent_byteenable;    // mm_interconnect_0:NIOSV_FreeRTOS_timer_sw_agent_byteenable -> NIOSV_FreeRTOS:timer_sw_agent_byteenable
	wire         mm_interconnect_0_niosv_freertos_timer_sw_agent_readdatavalid; // NIOSV_FreeRTOS:timer_sw_agent_readdatavalid -> mm_interconnect_0:NIOSV_FreeRTOS_timer_sw_agent_readdatavalid
	wire         mm_interconnect_0_niosv_freertos_timer_sw_agent_write;         // mm_interconnect_0:NIOSV_FreeRTOS_timer_sw_agent_write -> NIOSV_FreeRTOS:timer_sw_agent_write
	wire  [31:0] mm_interconnect_0_niosv_freertos_timer_sw_agent_writedata;     // mm_interconnect_0:NIOSV_FreeRTOS_timer_sw_agent_writedata -> NIOSV_FreeRTOS:timer_sw_agent_writedata
	wire         irq_mapper_receiver0_irq;                                      // DEBUG:av_irq -> irq_mapper:receiver0_irq
	wire  [15:0] niosv_freertos_platform_irq_rx_irq;                            // irq_mapper:sender_irq -> NIOSV_FreeRTOS:platform_irq_rx_irq
	wire         rst_controller_reset_out_reset;                                // rst_controller:reset_out -> [BUTTONS:reset_n, DEBUG:rst_n, LEDs:reset_n, NIOSV_FreeRTOS:reset_reset, SDRAM:reset_n, irq_mapper:reset, mm_interconnect_0:NIOSV_FreeRTOS_reset_reset_bridge_in_reset_reset]

	Lab4_BUTTONS buttons (
		.clk      (clocks_sys_clk_clk),                    //                 clk.clk
		.reset_n  (~rst_controller_reset_out_reset),       //               reset.reset_n
		.address  (mm_interconnect_0_buttons_s1_address),  //                  s1.address
		.readdata (mm_interconnect_0_buttons_s1_readdata), //                    .readdata
		.in_port  (buttons_export)                         // external_connection.export
	);

	Lab4_CLOCKS clocks (
		.ref_clk_clk        (clk_clk),                            //      ref_clk.clk
		.ref_reset_reset    (niosv_freertos_dbg_reset_out_reset), //    ref_reset.reset
		.sys_clk_clk        (clocks_sys_clk_clk),                 //      sys_clk.clk
		.sdram_clk_clk      (sdram_clk_clk),                      //    sdram_clk.clk
		.reset_source_reset ()                                    // reset_source.reset
	);

	Lab4_DEBUG debug (
		.clk            (clocks_sys_clk_clk),                                    //               clk.clk
		.rst_n          (~rst_controller_reset_out_reset),                       //             reset.reset_n
		.av_chipselect  (mm_interconnect_0_debug_avalon_jtag_slave_chipselect),  // avalon_jtag_slave.chipselect
		.av_address     (mm_interconnect_0_debug_avalon_jtag_slave_address),     //                  .address
		.av_read_n      (~mm_interconnect_0_debug_avalon_jtag_slave_read),       //                  .read_n
		.av_readdata    (mm_interconnect_0_debug_avalon_jtag_slave_readdata),    //                  .readdata
		.av_write_n     (~mm_interconnect_0_debug_avalon_jtag_slave_write),      //                  .write_n
		.av_writedata   (mm_interconnect_0_debug_avalon_jtag_slave_writedata),   //                  .writedata
		.av_waitrequest (mm_interconnect_0_debug_avalon_jtag_slave_waitrequest), //                  .waitrequest
		.av_irq         (irq_mapper_receiver0_irq)                               //               irq.irq
	);

	Lab4_LEDs leds (
		.clk        (clocks_sys_clk_clk),                   //                 clk.clk
		.reset_n    (~rst_controller_reset_out_reset),      //               reset.reset_n
		.address    (mm_interconnect_0_leds_s1_address),    //                  s1.address
		.write_n    (~mm_interconnect_0_leds_s1_write),     //                    .write_n
		.writedata  (mm_interconnect_0_leds_s1_writedata),  //                    .writedata
		.chipselect (mm_interconnect_0_leds_s1_chipselect), //                    .chipselect
		.readdata   (mm_interconnect_0_leds_s1_readdata),   //                    .readdata
		.out_port   (leds_export)                           // external_connection.export
	);

	Lab4_NIOSV_FreeRTOS niosv_freertos (
		.clk                          (clocks_sys_clk_clk),                                            //                 clk.clk
		.reset_reset                  (rst_controller_reset_out_reset),                                //               reset.reset
		.platform_irq_rx_irq          (niosv_freertos_platform_irq_rx_irq),                            //     platform_irq_rx.irq
		.ndm_reset_in_reset           (niosv_freertos_dbg_reset_out_reset),                            //        ndm_reset_in.reset
		.timer_sw_agent_write         (mm_interconnect_0_niosv_freertos_timer_sw_agent_write),         //      timer_sw_agent.write
		.timer_sw_agent_writedata     (mm_interconnect_0_niosv_freertos_timer_sw_agent_writedata),     //                    .writedata
		.timer_sw_agent_byteenable    (mm_interconnect_0_niosv_freertos_timer_sw_agent_byteenable),    //                    .byteenable
		.timer_sw_agent_address       (mm_interconnect_0_niosv_freertos_timer_sw_agent_address),       //                    .address
		.timer_sw_agent_read          (mm_interconnect_0_niosv_freertos_timer_sw_agent_read),          //                    .read
		.timer_sw_agent_readdata      (mm_interconnect_0_niosv_freertos_timer_sw_agent_readdata),      //                    .readdata
		.timer_sw_agent_readdatavalid (mm_interconnect_0_niosv_freertos_timer_sw_agent_readdatavalid), //                    .readdatavalid
		.timer_sw_agent_waitrequest   (mm_interconnect_0_niosv_freertos_timer_sw_agent_waitrequest),   //                    .waitrequest
		.instruction_manager_awaddr   (niosv_freertos_instruction_manager_awaddr),                     // instruction_manager.awaddr
		.instruction_manager_awprot   (niosv_freertos_instruction_manager_awprot),                     //                    .awprot
		.instruction_manager_awvalid  (niosv_freertos_instruction_manager_awvalid),                    //                    .awvalid
		.instruction_manager_awready  (niosv_freertos_instruction_manager_awready),                    //                    .awready
		.instruction_manager_wdata    (niosv_freertos_instruction_manager_wdata),                      //                    .wdata
		.instruction_manager_wstrb    (niosv_freertos_instruction_manager_wstrb),                      //                    .wstrb
		.instruction_manager_wvalid   (niosv_freertos_instruction_manager_wvalid),                     //                    .wvalid
		.instruction_manager_wready   (niosv_freertos_instruction_manager_wready),                     //                    .wready
		.instruction_manager_bresp    (niosv_freertos_instruction_manager_bresp),                      //                    .bresp
		.instruction_manager_bvalid   (niosv_freertos_instruction_manager_bvalid),                     //                    .bvalid
		.instruction_manager_bready   (niosv_freertos_instruction_manager_bready),                     //                    .bready
		.instruction_manager_araddr   (niosv_freertos_instruction_manager_araddr),                     //                    .araddr
		.instruction_manager_arprot   (niosv_freertos_instruction_manager_arprot),                     //                    .arprot
		.instruction_manager_arvalid  (niosv_freertos_instruction_manager_arvalid),                    //                    .arvalid
		.instruction_manager_arready  (niosv_freertos_instruction_manager_arready),                    //                    .arready
		.instruction_manager_rdata    (niosv_freertos_instruction_manager_rdata),                      //                    .rdata
		.instruction_manager_rresp    (niosv_freertos_instruction_manager_rresp),                      //                    .rresp
		.instruction_manager_rvalid   (niosv_freertos_instruction_manager_rvalid),                     //                    .rvalid
		.instruction_manager_rready   (niosv_freertos_instruction_manager_rready),                     //                    .rready
		.data_manager_awaddr          (niosv_freertos_data_manager_awaddr),                            //        data_manager.awaddr
		.data_manager_awprot          (niosv_freertos_data_manager_awprot),                            //                    .awprot
		.data_manager_awvalid         (niosv_freertos_data_manager_awvalid),                           //                    .awvalid
		.data_manager_awready         (niosv_freertos_data_manager_awready),                           //                    .awready
		.data_manager_wdata           (niosv_freertos_data_manager_wdata),                             //                    .wdata
		.data_manager_wstrb           (niosv_freertos_data_manager_wstrb),                             //                    .wstrb
		.data_manager_wvalid          (niosv_freertos_data_manager_wvalid),                            //                    .wvalid
		.data_manager_wready          (niosv_freertos_data_manager_wready),                            //                    .wready
		.data_manager_bresp           (niosv_freertos_data_manager_bresp),                             //                    .bresp
		.data_manager_bvalid          (niosv_freertos_data_manager_bvalid),                            //                    .bvalid
		.data_manager_bready          (niosv_freertos_data_manager_bready),                            //                    .bready
		.data_manager_araddr          (niosv_freertos_data_manager_araddr),                            //                    .araddr
		.data_manager_arprot          (niosv_freertos_data_manager_arprot),                            //                    .arprot
		.data_manager_arvalid         (niosv_freertos_data_manager_arvalid),                           //                    .arvalid
		.data_manager_arready         (niosv_freertos_data_manager_arready),                           //                    .arready
		.data_manager_rdata           (niosv_freertos_data_manager_rdata),                             //                    .rdata
		.data_manager_rresp           (niosv_freertos_data_manager_rresp),                             //                    .rresp
		.data_manager_rvalid          (niosv_freertos_data_manager_rvalid),                            //                    .rvalid
		.data_manager_rready          (niosv_freertos_data_manager_rready),                            //                    .rready
		.dm_agent_write               (mm_interconnect_0_niosv_freertos_dm_agent_write),               //            dm_agent.write
		.dm_agent_writedata           (mm_interconnect_0_niosv_freertos_dm_agent_writedata),           //                    .writedata
		.dm_agent_address             (mm_interconnect_0_niosv_freertos_dm_agent_address),             //                    .address
		.dm_agent_read                (mm_interconnect_0_niosv_freertos_dm_agent_read),                //                    .read
		.dm_agent_readdata            (mm_interconnect_0_niosv_freertos_dm_agent_readdata),            //                    .readdata
		.dm_agent_readdatavalid       (mm_interconnect_0_niosv_freertos_dm_agent_readdatavalid),       //                    .readdatavalid
		.dm_agent_waitrequest         (mm_interconnect_0_niosv_freertos_dm_agent_waitrequest),         //                    .waitrequest
		.dbg_reset_out_reset          (niosv_freertos_dbg_reset_out_reset)                             //       dbg_reset_out.reset
	);

	Lab4_SDRAM sdram (
		.clk            (clocks_sys_clk_clk),                       //   clk.clk
		.reset_n        (~rst_controller_reset_out_reset),          // reset.reset_n
		.az_addr        (mm_interconnect_0_sdram_s1_address),       //    s1.address
		.az_be_n        (~mm_interconnect_0_sdram_s1_byteenable),   //      .byteenable_n
		.az_cs          (mm_interconnect_0_sdram_s1_chipselect),    //      .chipselect
		.az_data        (mm_interconnect_0_sdram_s1_writedata),     //      .writedata
		.az_rd_n        (~mm_interconnect_0_sdram_s1_read),         //      .read_n
		.az_wr_n        (~mm_interconnect_0_sdram_s1_write),        //      .write_n
		.za_data        (mm_interconnect_0_sdram_s1_readdata),      //      .readdata
		.za_valid       (mm_interconnect_0_sdram_s1_readdatavalid), //      .readdatavalid
		.za_waitrequest (mm_interconnect_0_sdram_s1_waitrequest),   //      .waitrequest
		.zs_addr        (sdram_wire_addr),                          //  wire.export
		.zs_ba          (sdram_wire_ba),                            //      .export
		.zs_cas_n       (sdram_wire_cas_n),                         //      .export
		.zs_cke         (sdram_wire_cke),                           //      .export
		.zs_cs_n        (sdram_wire_cs_n),                          //      .export
		.zs_dq          (sdram_wire_dq),                            //      .export
		.zs_dqm         (sdram_wire_dqm),                           //      .export
		.zs_ras_n       (sdram_wire_ras_n),                         //      .export
		.zs_we_n        (sdram_wire_we_n)                           //      .export
	);

	Lab4_mm_interconnect_0 mm_interconnect_0 (
		.NIOSV_FreeRTOS_data_manager_awaddr               (niosv_freertos_data_manager_awaddr),                            //                NIOSV_FreeRTOS_data_manager.awaddr
		.NIOSV_FreeRTOS_data_manager_awprot               (niosv_freertos_data_manager_awprot),                            //                                           .awprot
		.NIOSV_FreeRTOS_data_manager_awvalid              (niosv_freertos_data_manager_awvalid),                           //                                           .awvalid
		.NIOSV_FreeRTOS_data_manager_awready              (niosv_freertos_data_manager_awready),                           //                                           .awready
		.NIOSV_FreeRTOS_data_manager_wdata                (niosv_freertos_data_manager_wdata),                             //                                           .wdata
		.NIOSV_FreeRTOS_data_manager_wstrb                (niosv_freertos_data_manager_wstrb),                             //                                           .wstrb
		.NIOSV_FreeRTOS_data_manager_wvalid               (niosv_freertos_data_manager_wvalid),                            //                                           .wvalid
		.NIOSV_FreeRTOS_data_manager_wready               (niosv_freertos_data_manager_wready),                            //                                           .wready
		.NIOSV_FreeRTOS_data_manager_bresp                (niosv_freertos_data_manager_bresp),                             //                                           .bresp
		.NIOSV_FreeRTOS_data_manager_bvalid               (niosv_freertos_data_manager_bvalid),                            //                                           .bvalid
		.NIOSV_FreeRTOS_data_manager_bready               (niosv_freertos_data_manager_bready),                            //                                           .bready
		.NIOSV_FreeRTOS_data_manager_araddr               (niosv_freertos_data_manager_araddr),                            //                                           .araddr
		.NIOSV_FreeRTOS_data_manager_arprot               (niosv_freertos_data_manager_arprot),                            //                                           .arprot
		.NIOSV_FreeRTOS_data_manager_arvalid              (niosv_freertos_data_manager_arvalid),                           //                                           .arvalid
		.NIOSV_FreeRTOS_data_manager_arready              (niosv_freertos_data_manager_arready),                           //                                           .arready
		.NIOSV_FreeRTOS_data_manager_rdata                (niosv_freertos_data_manager_rdata),                             //                                           .rdata
		.NIOSV_FreeRTOS_data_manager_rresp                (niosv_freertos_data_manager_rresp),                             //                                           .rresp
		.NIOSV_FreeRTOS_data_manager_rvalid               (niosv_freertos_data_manager_rvalid),                            //                                           .rvalid
		.NIOSV_FreeRTOS_data_manager_rready               (niosv_freertos_data_manager_rready),                            //                                           .rready
		.NIOSV_FreeRTOS_instruction_manager_awaddr        (niosv_freertos_instruction_manager_awaddr),                     //         NIOSV_FreeRTOS_instruction_manager.awaddr
		.NIOSV_FreeRTOS_instruction_manager_awprot        (niosv_freertos_instruction_manager_awprot),                     //                                           .awprot
		.NIOSV_FreeRTOS_instruction_manager_awvalid       (niosv_freertos_instruction_manager_awvalid),                    //                                           .awvalid
		.NIOSV_FreeRTOS_instruction_manager_awready       (niosv_freertos_instruction_manager_awready),                    //                                           .awready
		.NIOSV_FreeRTOS_instruction_manager_wdata         (niosv_freertos_instruction_manager_wdata),                      //                                           .wdata
		.NIOSV_FreeRTOS_instruction_manager_wstrb         (niosv_freertos_instruction_manager_wstrb),                      //                                           .wstrb
		.NIOSV_FreeRTOS_instruction_manager_wvalid        (niosv_freertos_instruction_manager_wvalid),                     //                                           .wvalid
		.NIOSV_FreeRTOS_instruction_manager_wready        (niosv_freertos_instruction_manager_wready),                     //                                           .wready
		.NIOSV_FreeRTOS_instruction_manager_bresp         (niosv_freertos_instruction_manager_bresp),                      //                                           .bresp
		.NIOSV_FreeRTOS_instruction_manager_bvalid        (niosv_freertos_instruction_manager_bvalid),                     //                                           .bvalid
		.NIOSV_FreeRTOS_instruction_manager_bready        (niosv_freertos_instruction_manager_bready),                     //                                           .bready
		.NIOSV_FreeRTOS_instruction_manager_araddr        (niosv_freertos_instruction_manager_araddr),                     //                                           .araddr
		.NIOSV_FreeRTOS_instruction_manager_arprot        (niosv_freertos_instruction_manager_arprot),                     //                                           .arprot
		.NIOSV_FreeRTOS_instruction_manager_arvalid       (niosv_freertos_instruction_manager_arvalid),                    //                                           .arvalid
		.NIOSV_FreeRTOS_instruction_manager_arready       (niosv_freertos_instruction_manager_arready),                    //                                           .arready
		.NIOSV_FreeRTOS_instruction_manager_rdata         (niosv_freertos_instruction_manager_rdata),                      //                                           .rdata
		.NIOSV_FreeRTOS_instruction_manager_rresp         (niosv_freertos_instruction_manager_rresp),                      //                                           .rresp
		.NIOSV_FreeRTOS_instruction_manager_rvalid        (niosv_freertos_instruction_manager_rvalid),                     //                                           .rvalid
		.NIOSV_FreeRTOS_instruction_manager_rready        (niosv_freertos_instruction_manager_rready),                     //                                           .rready
		.CLOCKS_sys_clk_clk                               (clocks_sys_clk_clk),                                            //                             CLOCKS_sys_clk.clk
		.NIOSV_FreeRTOS_reset_reset_bridge_in_reset_reset (rst_controller_reset_out_reset),                                // NIOSV_FreeRTOS_reset_reset_bridge_in_reset.reset
		.BUTTONS_s1_address                               (mm_interconnect_0_buttons_s1_address),                          //                                 BUTTONS_s1.address
		.BUTTONS_s1_readdata                              (mm_interconnect_0_buttons_s1_readdata),                         //                                           .readdata
		.DEBUG_avalon_jtag_slave_address                  (mm_interconnect_0_debug_avalon_jtag_slave_address),             //                    DEBUG_avalon_jtag_slave.address
		.DEBUG_avalon_jtag_slave_write                    (mm_interconnect_0_debug_avalon_jtag_slave_write),               //                                           .write
		.DEBUG_avalon_jtag_slave_read                     (mm_interconnect_0_debug_avalon_jtag_slave_read),                //                                           .read
		.DEBUG_avalon_jtag_slave_readdata                 (mm_interconnect_0_debug_avalon_jtag_slave_readdata),            //                                           .readdata
		.DEBUG_avalon_jtag_slave_writedata                (mm_interconnect_0_debug_avalon_jtag_slave_writedata),           //                                           .writedata
		.DEBUG_avalon_jtag_slave_waitrequest              (mm_interconnect_0_debug_avalon_jtag_slave_waitrequest),         //                                           .waitrequest
		.DEBUG_avalon_jtag_slave_chipselect               (mm_interconnect_0_debug_avalon_jtag_slave_chipselect),          //                                           .chipselect
		.LEDs_s1_address                                  (mm_interconnect_0_leds_s1_address),                             //                                    LEDs_s1.address
		.LEDs_s1_write                                    (mm_interconnect_0_leds_s1_write),                               //                                           .write
		.LEDs_s1_readdata                                 (mm_interconnect_0_leds_s1_readdata),                            //                                           .readdata
		.LEDs_s1_writedata                                (mm_interconnect_0_leds_s1_writedata),                           //                                           .writedata
		.LEDs_s1_chipselect                               (mm_interconnect_0_leds_s1_chipselect),                          //                                           .chipselect
		.NIOSV_FreeRTOS_dm_agent_address                  (mm_interconnect_0_niosv_freertos_dm_agent_address),             //                    NIOSV_FreeRTOS_dm_agent.address
		.NIOSV_FreeRTOS_dm_agent_write                    (mm_interconnect_0_niosv_freertos_dm_agent_write),               //                                           .write
		.NIOSV_FreeRTOS_dm_agent_read                     (mm_interconnect_0_niosv_freertos_dm_agent_read),                //                                           .read
		.NIOSV_FreeRTOS_dm_agent_readdata                 (mm_interconnect_0_niosv_freertos_dm_agent_readdata),            //                                           .readdata
		.NIOSV_FreeRTOS_dm_agent_writedata                (mm_interconnect_0_niosv_freertos_dm_agent_writedata),           //                                           .writedata
		.NIOSV_FreeRTOS_dm_agent_readdatavalid            (mm_interconnect_0_niosv_freertos_dm_agent_readdatavalid),       //                                           .readdatavalid
		.NIOSV_FreeRTOS_dm_agent_waitrequest              (mm_interconnect_0_niosv_freertos_dm_agent_waitrequest),         //                                           .waitrequest
		.NIOSV_FreeRTOS_timer_sw_agent_address            (mm_interconnect_0_niosv_freertos_timer_sw_agent_address),       //              NIOSV_FreeRTOS_timer_sw_agent.address
		.NIOSV_FreeRTOS_timer_sw_agent_write              (mm_interconnect_0_niosv_freertos_timer_sw_agent_write),         //                                           .write
		.NIOSV_FreeRTOS_timer_sw_agent_read               (mm_interconnect_0_niosv_freertos_timer_sw_agent_read),          //                                           .read
		.NIOSV_FreeRTOS_timer_sw_agent_readdata           (mm_interconnect_0_niosv_freertos_timer_sw_agent_readdata),      //                                           .readdata
		.NIOSV_FreeRTOS_timer_sw_agent_writedata          (mm_interconnect_0_niosv_freertos_timer_sw_agent_writedata),     //                                           .writedata
		.NIOSV_FreeRTOS_timer_sw_agent_byteenable         (mm_interconnect_0_niosv_freertos_timer_sw_agent_byteenable),    //                                           .byteenable
		.NIOSV_FreeRTOS_timer_sw_agent_readdatavalid      (mm_interconnect_0_niosv_freertos_timer_sw_agent_readdatavalid), //                                           .readdatavalid
		.NIOSV_FreeRTOS_timer_sw_agent_waitrequest        (mm_interconnect_0_niosv_freertos_timer_sw_agent_waitrequest),   //                                           .waitrequest
		.SDRAM_s1_address                                 (mm_interconnect_0_sdram_s1_address),                            //                                   SDRAM_s1.address
		.SDRAM_s1_write                                   (mm_interconnect_0_sdram_s1_write),                              //                                           .write
		.SDRAM_s1_read                                    (mm_interconnect_0_sdram_s1_read),                               //                                           .read
		.SDRAM_s1_readdata                                (mm_interconnect_0_sdram_s1_readdata),                           //                                           .readdata
		.SDRAM_s1_writedata                               (mm_interconnect_0_sdram_s1_writedata),                          //                                           .writedata
		.SDRAM_s1_byteenable                              (mm_interconnect_0_sdram_s1_byteenable),                         //                                           .byteenable
		.SDRAM_s1_readdatavalid                           (mm_interconnect_0_sdram_s1_readdatavalid),                      //                                           .readdatavalid
		.SDRAM_s1_waitrequest                             (mm_interconnect_0_sdram_s1_waitrequest),                        //                                           .waitrequest
		.SDRAM_s1_chipselect                              (mm_interconnect_0_sdram_s1_chipselect)                          //                                           .chipselect
	);

	Lab4_irq_mapper irq_mapper (
		.clk           (clocks_sys_clk_clk),                 //       clk.clk
		.reset         (rst_controller_reset_out_reset),     // clk_reset.reset
		.receiver0_irq (irq_mapper_receiver0_irq),           // receiver0.irq
		.sender_irq    (niosv_freertos_platform_irq_rx_irq)  //    sender.irq
	);

	altera_reset_controller #(
		.NUM_RESET_INPUTS          (1),
		.OUTPUT_RESET_SYNC_EDGES   ("deassert"),
		.SYNC_DEPTH                (2),
		.RESET_REQUEST_PRESENT     (0),
		.RESET_REQ_WAIT_TIME       (1),
		.MIN_RST_ASSERTION_TIME    (3),
		.RESET_REQ_EARLY_DSRT_TIME (1),
		.USE_RESET_REQUEST_IN0     (0),
		.USE_RESET_REQUEST_IN1     (0),
		.USE_RESET_REQUEST_IN2     (0),
		.USE_RESET_REQUEST_IN3     (0),
		.USE_RESET_REQUEST_IN4     (0),
		.USE_RESET_REQUEST_IN5     (0),
		.USE_RESET_REQUEST_IN6     (0),
		.USE_RESET_REQUEST_IN7     (0),
		.USE_RESET_REQUEST_IN8     (0),
		.USE_RESET_REQUEST_IN9     (0),
		.USE_RESET_REQUEST_IN10    (0),
		.USE_RESET_REQUEST_IN11    (0),
		.USE_RESET_REQUEST_IN12    (0),
		.USE_RESET_REQUEST_IN13    (0),
		.USE_RESET_REQUEST_IN14    (0),
		.USE_RESET_REQUEST_IN15    (0),
		.ADAPT_RESET_REQUEST       (0)
	) rst_controller (
		.reset_in0      (niosv_freertos_dbg_reset_out_reset), // reset_in0.reset
		.clk            (clocks_sys_clk_clk),                 //       clk.clk
		.reset_out      (rst_controller_reset_out_reset),     // reset_out.reset
		.reset_req      (),                                   // (terminated)
		.reset_req_in0  (1'b0),                               // (terminated)
		.reset_in1      (1'b0),                               // (terminated)
		.reset_req_in1  (1'b0),                               // (terminated)
		.reset_in2      (1'b0),                               // (terminated)
		.reset_req_in2  (1'b0),                               // (terminated)
		.reset_in3      (1'b0),                               // (terminated)
		.reset_req_in3  (1'b0),                               // (terminated)
		.reset_in4      (1'b0),                               // (terminated)
		.reset_req_in4  (1'b0),                               // (terminated)
		.reset_in5      (1'b0),                               // (terminated)
		.reset_req_in5  (1'b0),                               // (terminated)
		.reset_in6      (1'b0),                               // (terminated)
		.reset_req_in6  (1'b0),                               // (terminated)
		.reset_in7      (1'b0),                               // (terminated)
		.reset_req_in7  (1'b0),                               // (terminated)
		.reset_in8      (1'b0),                               // (terminated)
		.reset_req_in8  (1'b0),                               // (terminated)
		.reset_in9      (1'b0),                               // (terminated)
		.reset_req_in9  (1'b0),                               // (terminated)
		.reset_in10     (1'b0),                               // (terminated)
		.reset_req_in10 (1'b0),                               // (terminated)
		.reset_in11     (1'b0),                               // (terminated)
		.reset_req_in11 (1'b0),                               // (terminated)
		.reset_in12     (1'b0),                               // (terminated)
		.reset_req_in12 (1'b0),                               // (terminated)
		.reset_in13     (1'b0),                               // (terminated)
		.reset_req_in13 (1'b0),                               // (terminated)
		.reset_in14     (1'b0),                               // (terminated)
		.reset_req_in14 (1'b0),                               // (terminated)
		.reset_in15     (1'b0),                               // (terminated)
		.reset_req_in15 (1'b0)                                // (terminated)
	);

endmodule
